/* ==========================================================================
   MARVEL 宇宙观影指挥中心 — 数据库
   数据整理截至 2026 年中;未上映作品的档期以官方最新公布为准。
   ========================================================================== */

window.MARVEL = window.MARVEL || {};

/* ---------- 阶段定义 ---------- */
MARVEL.PHASES = {
  1: { name: '第一阶段', en: 'PHASE 1', color: '#e62429', saga: 'infinity',   desc: '英雄初登场:六位创始复仇者逐一亮相,最终首次集结。' },
  2: { name: '第二阶段', en: 'PHASE 2', color: '#ff7a1a', saga: 'infinity',   desc: '纽约之战后的余波:神盾局崩塌、银河系登场、奥创危机。' },
  3: { name: '第三阶段', en: 'PHASE 3', color: '#9b59ff', saga: 'infinity',   desc: '英雄内战撕裂联盟,灭霸降临,无限传奇迎来终局。' },
  4: { name: '第四阶段', en: 'PHASE 4', color: '#22c1dc', saga: 'multiverse', desc: '终局之战后的新篇章:多元宇宙之门开启,新生代英雄登台。' },
  5: { name: '第五阶段', en: 'PHASE 5', color: '#4d7cfe', saga: 'multiverse', desc: '征服者与旧日传奇交锋,雷霆集结,通往毁灭日。' },
  6: { name: '第六阶段', en: 'PHASE 6', color: '#ffb300', saga: 'multiverse', desc: '神奇四侠登场,毁灭博士降临,多元宇宙传奇走向终局。' },
};

MARVEL.UNIVERSES = {
  mcu:         { name: '漫威电影宇宙', short: 'MCU', color: null },
  raimi:       { name: '雷米蜘蛛侠宇宙', short: '雷米版', color: '#3fae6a' },
  tasm:        { name: '超凡蜘蛛侠宇宙', short: '超凡版', color: '#2e8b8b' },
  xmen:        { name: 'X战警宇宙', short: 'X战警', color: '#c9a227' },
  sony:        { name: '索尼漫威宇宙', short: '索尼', color: '#6b7d8f' },
  netflix:     { name: '网飞街头英雄', short: '网飞', color: '#a03030' },
  spiderverse: { name: '蜘蛛侠:平行宇宙', short: '动画', color: '#ff5ca8' },
  tv:          { name: '漫威电视', short: '电视', color: '#5f7a99' },
};

MARVEL.SAGAS = {
  infinity:   { name: '无限传奇', en: 'THE INFINITY SAGA', desc: '2008–2019,以六颗无限宝石为暗线的宏大叙事,漫威电影宇宙的黄金十年。' },
  multiverse: { name: '多元宇宙传奇', en: 'THE MULTIVERSE SAGA', desc: '2021 至今,时间线分裂、多元宇宙碰撞,通往《毁灭日》与《秘密战争》。' },
  legacy:     { name: '前代与番外', en: 'LEGACY', desc: 'MCU 之外的漫威影视作品:老三部曲、X战警、网飞剧集等,多元宇宙的注脚。' },
};

/* ---------- 宇宙链路(地铁线路) ---------- */
MARVEL.THREADS = {
  avengers:   { name: '复仇者集结', color: '#e62429', emoji: '🅰️', desc: '从单人电影到六人集结,再到内战与终局——贯穿宇宙的主动脉。' },
  stones:     { name: '无限宝石', color: '#c77dff', emoji: '💎', desc: '六颗创世宝石散落宇宙,所有线索最终汇向灭霸的手套。' },
  shield:     { name: '神盾局与九头蛇', color: '#4d9fff', emoji: '🛰️', desc: '弗瑞局长的暗线布局、九头蛇的渗透与斯克鲁人的潜伏。' },
  multiverse: { name: '多元宇宙', color: '#3ecf8e', emoji: '🌀', desc: '时间劫案打开的潘多拉魔盒:分支时间线、变体与入侵事件。' },
  spiderman:  { name: '蜘蛛侠', color: '#ff5ca8', emoji: '🕷️', desc: '小蜘蛛的成长三部曲,以及横跨三代蜘蛛侠的多元宇宙同框。' },
  asgard:     { name: '阿斯加德', color: '#f0b429', emoji: '⚡', desc: '雷神的家族恩怨与诸神黄昏,洛基的千面人生。' },
  cosmic:     { name: '宇宙远征', color: '#ff7a1a', emoji: '🚀', desc: '银河护卫队、克里帝国与惊奇队长——地球之外的漫威宇宙。' },
  mystic:     { name: '魔法至尊', color: '#22c1dc', emoji: '🔮', desc: '至圣所、黑暗维度、混沌魔法:神秘法术侧的力量版图。' },
  newgen:     { name: '新生代与雷霆', color: '#b0bec5', emoji: '🛡️', desc: '初代谢幕之后:接棒的新英雄、政府棋局与雷霆特攻队。' },
};

/* ---------- 无限宝石(收集系统) ---------- */
MARVEL.STONES = [
  { id: 'space',   name: '空间宝石', color: '#4d9fff', workId: 'cap-1',          src: '美国队长' },
  { id: 'reality', name: '现实宝石', color: '#ff4d4d', workId: 'thor-2',         src: '雷神2' },
  { id: 'power',   name: '力量宝石', color: '#b44dff', workId: 'gotg',           src: '银河护卫队' },
  { id: 'mind',    name: '心灵宝石', color: '#ffd84d', workId: 'aou',            src: '复联2' },
  { id: 'time',    name: '时间宝石', color: '#4dff9d', workId: 'doctor-strange', src: '奇异博士' },
  { id: 'soul',    name: '灵魂宝石', color: '#ff9d4d', workId: 'infinity-war',   src: '复联3' },
];

/* ---------- 作品数据库 ----------
   type: movie 电影 / series 剧集 / special 特别篇 / anim 动画剧
   tier: core 主线必看 / recommended 推荐观看 / optional 选看补充
   chron: 故事时间线排序(null = 时间之外/非 MCU 主线)
------------------------------------------------------------------ */
MARVEL.WORKS = [

/* ================= 第一阶段 ================= */
{
  id: 'iron-man', title: '钢铁侠', enTitle: 'Iron Man', type: 'movie', universe: 'mcu',
  phase: 1, release: '2008-05-02', chron: 30, storyYear: '2010', runtime: 126, tier: 'core',
  rating: 7.9, emoji: '🦾',
  tagline: '一切开始的地方。「我就是钢铁侠。」',
  synopsis: '军火大亨托尼·斯塔克在阿富汗遇袭被俘,靠胸口的方舟反应堆保命。他在山洞中打造出第一代装甲逃出生天,回国后决定亲手终结自己造成的乱局。',
  whyWatch: 'MCU 的创世之作,奠定了整个宇宙「接地气超英」的基调。片尾一句台词打破超英电影三十年的规矩,片尾彩蛋更是宣告了一个宏大计划的开始。',
  prereq: [], leadsTo: ['iron-man-2', 'avengers'],
  threads: ['avengers', 'shield'], characters: ['钢铁侠', '托尼·斯塔克', '小辣椒', '战争机器', '尼克·弗瑞'],
  postCredits: 1, eggTip: '片尾弗瑞局长登场,首次说出「复仇者计划」——留到最后!',
},
{
  id: 'hulk', title: '无敌浩克', enTitle: 'The Incredible Hulk', type: 'movie', universe: 'mcu',
  phase: 1, release: '2008-06-13', chron: 50, storyYear: '2011', runtime: 112, tier: 'optional',
  rating: 6.6, emoji: '💚',
  tagline: '被宇宙遗忘的第二部 MCU 电影。',
  synopsis: '物理学家布鲁斯·班纳因伽马射线实验事故,愤怒时会变成绿色巨人。他一边逃避罗斯将军的追捕,一边寻找治愈之法,最终不得不直面「憎恶」。',
  whyWatch: '存在感最低的 MCU 电影(主演后来还换人了),但罗斯将军与「憎恶」在几十年后的《美队4》《女浩克》中回归,补看会有惊喜。时间紧可跳过。',
  prereq: [], leadsTo: ['brave-new-world'],
  threads: [], characters: ['浩克', '布鲁斯·班纳', '罗斯将军', '憎恶'],
  postCredits: 1, eggTip: '片尾托尼·斯塔克现身酒吧,与罗斯将军搭话——早期宇宙联动的尝试。',
},
{
  id: 'iron-man-2', title: '钢铁侠2', enTitle: 'Iron Man 2', type: 'movie', universe: 'mcu',
  phase: 1, release: '2010-05-07', chron: 40, storyYear: '2011', runtime: 124, tier: 'recommended',
  rating: 6.9, emoji: '🏎️',
  tagline: '黑寡妇初登场,钢铁侠的中年危机。',
  synopsis: '公开身份后的托尼风光无限,却被反应堆的钯元素慢性毒害。俄罗斯物理学家之子「鞭索」携电鞭复仇,军方与对手虎视眈眈,托尼必须找到新元素自救。',
  whyWatch: '黑寡妇娜塔莎首次登场,战争机器正式披挂,神盾局戏份大增。剧情略平,但对理解复联的组建过程很有帮助。',
  prereq: ['iron-man'], leadsTo: ['avengers'],
  threads: ['avengers', 'shield'], characters: ['钢铁侠', '黑寡妇', '战争机器', '尼克·弗瑞', '鞭索'],
  postCredits: 1, eggTip: '片尾新墨西哥沙漠中出现一把锤子——雷神的预告。',
},
{
  id: 'thor', title: '雷神', enTitle: 'Thor', type: 'movie', universe: 'mcu',
  phase: 1, release: '2011-05-06', chron: 60, storyYear: '2011', runtime: 115, tier: 'core',
  rating: 7.0, emoji: '🔨',
  tagline: '诸神降临地球,MCU 从科幻迈向神话。',
  synopsis: '傲慢的阿斯加德王子索尔因挑起战端被奥丁放逐地球,失去神力。当弟弟洛基的阴谋浮出水面,他必须证明自己配得上雷神之锤。',
  whyWatch: '洛基——整个 MCU 人气最高的反派/亦正亦邪角色——在此登场。阿斯加德的设定也为宇宙魔方、无限宝石铺路。',
  prereq: [], leadsTo: ['avengers', 'thor-2'],
  threads: ['avengers', 'asgard'], characters: ['雷神', '索尔', '洛基', '奥丁', '简·福斯特', '鹰眼'],
  postCredits: 1, eggTip: '片尾弗瑞向塞尔维格博士展示宇宙魔方,洛基的倒影一闪而过。',
},
{
  id: 'cap-1', title: '美国队长', enTitle: 'Captain America: The First Avenger', type: 'movie', universe: 'mcu',
  phase: 1, release: '2011-07-22', chron: 10, storyYear: '1943-1945', runtime: 124, tier: 'core',
  rating: 6.9, emoji: '🛡️', stone: 'space',
  tagline: '故事时间线的起点:1943 年的超级士兵。',
  synopsis: '二战期间,瘦弱但正直的史蒂夫·罗杰斯接受超级士兵血清改造,成为美国队长。他率咆哮突击队对抗九头蛇的红骷髅,最终驾机坠入冰海,长眠七十年。',
  whyWatch: '整个 MCU 故事时间线的第一章。宇宙魔方(空间宝石)首次登场,九头蛇、卡特特工、冬兵巴基的羁绊都从这里开始。',
  prereq: [], leadsTo: ['avengers', 'cap-2'],
  threads: ['avengers', 'stones', 'shield'], characters: ['美国队长', '史蒂夫·罗杰斯', '巴基', '佩姬·卡特', '红骷髅', '霍华德·斯塔克'],
  postCredits: 1, eggTip: '片尾队长在现代醒来,弗瑞发出邀请——直接衔接《复仇者联盟》。',
},
{
  id: 'avengers', title: '复仇者联盟', enTitle: 'The Avengers', type: 'movie', universe: 'mcu',
  phase: 1, release: '2012-05-04', chron: 70, storyYear: '2012', runtime: 143, tier: 'core',
  rating: 8.0, emoji: '💥',
  tagline: '史上第一次,英雄们同框集结。',
  synopsis: '洛基携宇宙魔方与外星军团入侵地球,弗瑞局长启动复仇者计划。六位性格迥异的英雄从互相看不顺眼到并肩作战,在纽约上空打响载入影史的保卫战。',
  whyWatch: '超英电影史的里程碑,「复仇者,集结」的起点。纽约之战是此后无数作品反复回望的坐标原点,灭霸也在彩蛋中首次亮相。',
  prereq: ['iron-man', 'thor', 'cap-1'], leadsTo: ['iron-man-3', 'aou'],
  threads: ['avengers', 'stones', 'shield', 'asgard'], characters: ['钢铁侠', '美国队长', '雷神', '浩克', '黑寡妇', '鹰眼', '洛基', '尼克·弗瑞'],
  postCredits: 2, eggTip: '中段彩蛋灭霸首次露脸;片尾彩蛋是全员瘫坐吃沙威玛,漫威式幽默的起源。',
},

/* ================= 第二阶段 ================= */
{
  id: 'iron-man-3', title: '钢铁侠3', enTitle: 'Iron Man 3', type: 'movie', universe: 'mcu',
  phase: 2, release: '2013-05-03', chron: 80, storyYear: '2012圣诞', runtime: 130, tier: 'recommended',
  rating: 7.1, emoji: '🧨',
  tagline: '纽约之战后,托尼的创伤后应激。',
  synopsis: '纽约之战给托尼留下严重焦虑,他疯狂造甲不能自拔。神秘恐怖分子「满大人」制造连环爆炸,托尼的豪宅被夷为平地,他必须在一无所有中证明:装甲之下的人才是英雄。',
  whyWatch: '托尼个人弧光最完整的一部,「你可以夺走我的房子和装甲,但夺不走我是发明家」。对理解他在《奥创纪元》《内战》中的执念至关重要。',
  prereq: ['avengers'], leadsTo: ['aou'],
  threads: ['avengers'], characters: ['钢铁侠', '小辣椒', '战争机器', '满大人(冒牌)'],
  postCredits: 1, eggTip: '片尾揭晓托尼的倾诉对象是班纳博士——「我又不是那种医生」。',
},
{
  id: 'thor-2', title: '雷神2:黑暗世界', enTitle: 'Thor: The Dark World', type: 'movie', universe: 'mcu',
  phase: 2, release: '2013-11-08', chron: 90, storyYear: '2013', runtime: 112, tier: 'recommended',
  rating: 6.8, emoji: '🌑', stone: 'reality',
  tagline: '现实宝石登场,洛基的「牺牲」。',
  synopsis: '九界汇聚之际,黑暗精灵首领玛勒基斯苏醒,追寻藏于简·福斯特体内的「以太」(现实宝石)。索尔被迫与狱中的洛基联手,横跨世界树作战。',
  whyWatch: '口碑平平但地位关键:现实宝石在此登场,洛基的假死与夺位直接铺垫《诸神黄昏》,片尾彩蛋首次引出收藏家与「六颗宝石」的概念。',
  prereq: ['thor', 'avengers'], leadsTo: ['thor-ragnarok'],
  threads: ['stones', 'asgard'], characters: ['雷神', '洛基', '简·福斯特', '奥丁', '海姆达尔'],
  postCredits: 2, eggTip: '中段彩蛋:仙宫将以太交给收藏家,第一次明确「无限宝石」的存在。',
},
{
  id: 'cap-2', title: '美国队长2:冬日战士', enTitle: 'Captain America: The Winter Soldier', type: 'movie', universe: 'mcu',
  phase: 2, release: '2014-04-04', chron: 100, storyYear: '2014', runtime: 136, tier: 'core',
  rating: 7.8, emoji: '❄️',
  tagline: '公认的 MCU 最佳单人电影之一,政治惊悚风格。',
  synopsis: '为神盾局效力的队长发现组织内部溃烂已久——九头蛇渗透七十年,「洞察计划」即将启动。而受命追杀他的传奇杀手冬日战士,竟是他以为早已牺牲的挚友巴基。',
  whyWatch: '风格化最成功的 MCU 电影,神盾局在本片崩塌,直接改写宇宙格局(连带影响《神盾局特工》全剧)。猎鹰登场,队长与巴基的羁绊成为后续两部的主轴。',
  prereq: ['cap-1', 'avengers'], leadsTo: ['civil-war', 'falcon-ws'],
  threads: ['avengers', 'shield'], characters: ['美国队长', '冬兵', '巴基', '黑寡妇', '猎鹰', '尼克·弗瑞'],
  postCredits: 2, eggTip: '中段彩蛋:男爵斯特拉克的实验室里,「双子」旺达与快银首次亮相。',
},
{
  id: 'gotg', title: '银河护卫队', enTitle: 'Guardians of the Galaxy', type: 'movie', universe: 'mcu',
  phase: 2, release: '2014-08-01', chron: 110, storyYear: '2014', runtime: 121, tier: 'core',
  rating: 8.0, emoji: '🚀', stone: 'power',
  tagline: '一群混蛋拯救银河系,配乐封神。',
  synopsis: '地球混混「星爵」偷到一颗神秘球体,被赏金猎人火箭浣熊和格鲁特、复仇者卡魔拉、毁灭者德拉克斯盯上。五个失败者在监狱结成草台班子,却要阻止灭霸的爪牙罗南毁灭星球。',
  whyWatch: '把 MCU 版图从地球扩展到整个银河系,力量宝石与灭霸势力正面登场。《Awesome Mix》磁带配乐 + 贱萌团队人设,漫威最会玩的一支队伍。',
  prereq: [], leadsTo: ['gotg2', 'infinity-war'],
  threads: ['stones', 'cosmic'], characters: ['星爵', '卡魔拉', '火箭浣熊', '格鲁特', '德拉克斯', '灭霸', '涅布拉'],
  postCredits: 1, eggTip: '片尾收藏家的展馆里坐着一只……会说话的鸭子(霍华德鸭)。',
},
{
  id: 'aou', title: '复仇者联盟2:奥创纪元', enTitle: 'Avengers: Age of Ultron', type: 'movie', universe: 'mcu',
  phase: 2, release: '2015-05-01', chron: 130, storyYear: '2015', runtime: 141, tier: 'core',
  rating: 7.3, emoji: '🤖', stone: 'mind',
  tagline: '托尼亲手造出的噩梦,幻视诞生。',
  synopsis: '托尼用洛基权杖中的心灵宝石开发和平守护 AI「奥创」,结果它一觉醒来就判定人类是地球最大威胁。复仇者们辗转全球围剿奥创,幻视在此过程中诞生。',
  whyWatch: '心灵宝石正式定名,幻视与旺达加入战团,索科维亚事件直接引爆《内战》的政治危机,鹰眼的家庭线也在此展开。承上启下的关键节点。',
  prereq: ['avengers', 'iron-man-3'], leadsTo: ['civil-war', 'wandavision'],
  threads: ['avengers', 'stones', 'shield', 'asgard'], characters: ['钢铁侠', '美国队长', '雷神', '浩克', '黑寡妇', '鹰眼', '奥创', '幻视', '绯红女巫', '快银'],
  postCredits: 1, eggTip: '中段彩蛋:灭霸戴上无限手套,「看来只能亲自动手了」。',
},
{
  id: 'ant-man', title: '蚁人', enTitle: 'Ant-Man', type: 'movie', universe: 'mcu',
  phase: 2, release: '2015-07-17', chron: 140, storyYear: '2015', runtime: 117, tier: 'core',
  rating: 7.3, emoji: '🐜',
  tagline: '最小的英雄,最轻盈的盗贼喜剧。',
  synopsis: '刚出狱的窃贼斯科特·朗格被皮姆博士选中,穿上能缩小到蚂蚁大小的战衣,阻止皮姆粒子技术落入军火商之手,顺便当一个好爸爸。',
  whyWatch: '看似小品,实则埋下整个宇宙最重要的伏笔——量子领域。没有蚁人,就没有《终局之战》的时间劫案。轻松好笑,合家欢首选。',
  prereq: [], leadsTo: ['civil-war', 'ant-man-wasp'],
  threads: [], characters: ['蚁人', '斯科特·朗格', '皮姆博士', '黄蜂女', '猎鹰'],
  postCredits: 2, eggTip: '片尾彩蛋直接剪自《内战》:猎鹰找到了蚁人。',
},

/* ================= 第三阶段 ================= */
{
  id: 'civil-war', title: '美国队长3:内战', enTitle: 'Captain America: Civil War', type: 'movie', universe: 'mcu',
  phase: 3, release: '2016-05-06', chron: 150, storyYear: '2016', runtime: 147, tier: 'core',
  rating: 7.8, emoji: '⚔️',
  tagline: '英雄对英雄:机场大战,阵营对立。',
  synopsis: '《索科维亚协议》要求超级英雄接受政府监管,钢铁侠与美国队长立场决裂。冬兵被构陷为爆炸案凶手,队长执意庇护挚友,十二位英雄在机场分成两队正面开战。',
  whyWatch: '实质上的「复联2.5」:黑豹与新蜘蛛侠在此登场,托尼与队长的裂痕直到《终局之战》才弥合。机场大战是 MCU 群像调度的教科书。',
  prereq: ['cap-2', 'aou', 'ant-man'], leadsTo: ['black-panther', 'spider-man-1', 'infinity-war', 'black-widow'],
  threads: ['avengers', 'spiderman', 'newgen'], characters: ['美国队长', '钢铁侠', '冬兵', '黑豹', '蜘蛛侠', '黑寡妇', '猎鹰', '蚁人', '绯红女巫', '幻视', '泽莫男爵'],
  postCredits: 2, eggTip: '中段彩蛋巴基在瓦坎达冰封;片尾彩蛋是彼得·帕克摆弄战衣投影。',
},
{
  id: 'doctor-strange', title: '奇异博士', enTitle: 'Doctor Strange', type: 'movie', universe: 'mcu',
  phase: 3, release: '2016-11-04', chron: 190, storyYear: '2016-2017', runtime: 115, tier: 'core',
  rating: 7.5, emoji: '🌀', stone: 'time',
  tagline: '打开魔法世界的大门,视效万花筒。',
  synopsis: '天才而傲慢的神经外科医生斯特兰奇因车祸双手尽毁,寻医问药无果后前往尼泊尔卡玛泰姬,拜入古一门下修习法术,最终以时间宝石与黑暗维度讨价还价。',
  whyWatch: '时间宝石与魔法体系登场,至圣所、镜像空间等设定成为后续多元宇宙故事的基石。「多玛姆,我是来谈判的」是 MCU 最聪明的反套路结局之一。',
  prereq: [], leadsTo: ['thor-ragnarok', 'infinity-war', 'mom'],
  threads: ['stones', 'mystic'], characters: ['奇异博士', '斯特兰奇', '古一', '莫度', '王', '卡西利亚斯'],
  postCredits: 2, eggTip: '中段彩蛋斯特兰奇与雷神喝茶(接《雷神3》);片尾莫度黑化。',
},
{
  id: 'gotg2', title: '银河护卫队2', enTitle: 'Guardians of the Galaxy Vol. 2', type: 'movie', universe: 'mcu',
  phase: 3, release: '2017-05-05', chron: 120, storyYear: '2014', runtime: 136, tier: 'core',
  rating: 7.6, emoji: '🌌',
  tagline: '「他也许是你父亲,但不是你爸爸。」',
  synopsis: '星爵终于见到亲生父亲——天神族「伊戈」,却发现这场父子相认背后藏着吞噬宇宙的野心。养父勇度用一生诠释了何为真正的父亲。',
  whyWatch: '把太空歌剧拍成家庭伦理剧,勇度的箭与那句「他是你父亲,但不是你爸爸」足以封神。婴儿格鲁特可爱度爆表,五个彩蛋创系列之最。',
  prereq: ['gotg'], leadsTo: ['infinity-war', 'gotg3'],
  threads: ['cosmic'], characters: ['星爵', '卡魔拉', '火箭浣熊', '格鲁特', '德拉克斯', '勇度', '螳螂女', '涅布拉'],
  postCredits: 5, eggTip: '整整 5 个彩蛋:亚当·术士的茧、少年格鲁特、初代护卫队……别快进片尾!',
},
{
  id: 'spider-man-1', title: '蜘蛛侠:英雄归来', enTitle: 'Spider-Man: Homecoming', type: 'movie', universe: 'mcu',
  phase: 3, release: '2017-07-07', chron: 180, storyYear: '2016', runtime: 133, tier: 'core',
  rating: 7.4, emoji: '🕷️',
  tagline: '15 岁的高中生蜘蛛侠,回归校园。',
  synopsis: '内战之后,彼得·帕克天天盼着斯塔克先生再来召唤,却只能在皇后区抓抓自行车小偷。当他盯上倒卖外星武器的「秃鹫」,才明白当英雄不是靠战衣。',
  whyWatch: '荷兰弟蜘蛛侠首部单人电影,MCU 最青春的篇章。托尼与彼得的师徒关系是无限传奇后期最动人的情感线之一;中场那个「家长开门」的反转堪称年度惊吓。',
  prereq: ['civil-war'], leadsTo: ['infinity-war', 'spider-man-2'],
  threads: ['spiderman'], characters: ['蜘蛛侠', '彼得·帕克', '钢铁侠', '秃鹫', '梅姨', '内德', 'MJ'],
  postCredits: 2, eggTip: '片尾彩蛋是美国队长的「耐心」教育短片——专门嘲讽等彩蛋的你。',
},
{
  id: 'thor-ragnarok', title: '雷神3:诸神黄昏', enTitle: 'Thor: Ragnarok', type: 'movie', universe: 'mcu',
  phase: 3, release: '2017-11-03', chron: 200, storyYear: '2017', runtime: 130, tier: 'core',
  rating: 7.9, emoji: '⚡',
  tagline: '雷神系列画风突变:荒诞喜剧+电子乐。',
  synopsis: '死亡女神海拉回归,捏碎雷神之锤,阿斯加德危在旦夕。索尔流落角斗星球萨卡,与老同事浩克不打不相识,组「复仇者B队」杀回家园,却发现拯救故乡的方式是亲手毁掉它。',
  whyWatch: '塔伊加·维迪提把雷神系列从莎剧改造成霓虹喜剧,浩克大战雷神、Immigrant Song 配乐名场面不断。结尾直接无缝衔接《无限战争》开场。',
  prereq: ['thor-2', 'aou', 'doctor-strange'], leadsTo: ['infinity-war'],
  threads: ['asgard', 'mystic'], characters: ['雷神', '洛基', '浩克', '海拉', '女武神', '海姆达尔', '格兰德马斯特'],
  postCredits: 2, eggTip: '中段彩蛋:阿斯加德难民船遭遇灭霸的巨舰「圣殿2号」——噩梦开始。',
},
{
  id: 'black-panther', title: '黑豹', enTitle: 'Black Panther', type: 'movie', universe: 'mcu',
  phase: 3, release: '2018-02-16', chron: 170, storyYear: '2016-2017', runtime: 134, tier: 'core',
  rating: 7.3, emoji: '🐆',
  tagline: '瓦坎达万岁!奥斯卡最佳影片提名。',
  synopsis: '父亲死后,特查拉回到隐藏于非洲的高科技国度瓦坎达继承王位。流落海外的堂弟「埃里克·杀人魔」持复仇之心归来,挑战王座,也挑战瓦坎达闭关锁国的百年国策。',
  whyWatch: '首部提名奥斯卡最佳影片的超英电影。瓦坎达的世界观构建华丽,反派动机罕见地立得住。《无限战争》大决战的主战场就在这里。',
  prereq: ['civil-war'], leadsTo: ['infinity-war', 'wakanda-forever'],
  threads: ['newgen'], characters: ['黑豹', '特查拉', '苏睿', '奥科耶', '娜奇雅', '埃里克·杀人魔', '姆巴库'],
  postCredits: 2, eggTip: '片尾彩蛋:巴基在瓦坎达苏醒,被孩子们称为「白狼」。',
},
{
  id: 'infinity-war', title: '复仇者联盟3:无限战争', enTitle: 'Avengers: Infinity War', type: 'movie', universe: 'mcu',
  phase: 3, release: '2018-04-27', chron: 220, storyYear: '2018', runtime: 149, tier: 'core',
  rating: 8.4, emoji: '🧤', stone: 'soul',
  tagline: '灭霸来了。响指打了。一半人没了。',
  synopsis: '十年布局迎来收割:灭霸亲自出手集齐六颗无限宝石。复仇者与银河护卫队兵分多路阻击,从纽约打到泰坦星再到瓦坎达,却仍然没能挡住那个响指。',
  whyWatch: '十年二十部电影汇聚的顶点,以反派为主角的罕见叙事。结尾的化灰名场面让全球影院鸦雀无声——超英电影第一次让「英雄输了」成为定局。',
  prereq: ['civil-war', 'doctor-strange', 'gotg2', 'thor-ragnarok', 'black-panther', 'spider-man-1'], leadsTo: ['endgame'],
  threads: ['avengers', 'stones', 'spiderman', 'asgard', 'cosmic', 'mystic'], characters: ['灭霸', '钢铁侠', '奇异博士', '蜘蛛侠', '雷神', '星爵', '卡魔拉', '美国队长', '绯红女巫', '幻视', '黑豹'],
  postCredits: 1, eggTip: '片尾弗瑞化灰前发出求救信号,寻呼机上是惊奇队长的标志。',
},
{
  id: 'ant-man-wasp', title: '蚁人2:黄蜂女现身', enTitle: 'Ant-Man and the Wasp', type: 'movie', universe: 'mcu',
  phase: 3, release: '2018-07-06', chron: 210, storyYear: '2018', runtime: 118, tier: 'recommended',
  rating: 7.0, emoji: '🐝',
  tagline: '大战间隙的轻喜剧,但彩蛋是王炸。',
  synopsis: '内战后被软禁在家的斯科特只想安稳当爸爸,却被皮姆父女拉去营救困在量子领域三十年的初代黄蜂女珍妮特。正片轻松愉快——直到彩蛋。',
  whyWatch: '正片是调剂,彩蛋定乾坤:斯科特被困量子领域的瞬间,恰好是《终局之战》整个翻盘计划的钥匙。看《复联4》前务必补上这个彩蛋。',
  prereq: ['ant-man', 'civil-war'], leadsTo: ['endgame'],
  threads: [], characters: ['蚁人', '黄蜂女', '皮姆博士', '珍妮特', '幽灵'],
  postCredits: 2, eggTip: '中段彩蛋:皮姆一家化灰,斯科特被困量子领域——与《复联3》响指同步发生。',
},
{
  id: 'captain-marvel', title: '惊奇队长', enTitle: 'Captain Marvel', type: 'movie', universe: 'mcu',
  phase: 3, release: '2019-03-08', chron: 20, storyYear: '1995', runtime: 123, tier: 'recommended',
  rating: 6.8, emoji: '🌟',
  tagline: '90 年代前传:弗瑞的眼睛怎么瞎的。',
  synopsis: '克里帝国战士「弗斯」坠落 1995 年的地球,与年轻的神盾局特工弗瑞联手调查斯克鲁人渗透事件,逐渐找回自己作为地球飞行员卡罗尔·丹弗斯的记忆与真正的力量。',
  whyWatch: '解释《复联3》彩蛋里那台寻呼机的来历,补全弗瑞与「复仇者计划」命名的起源。噬元兽咕咕是全片最佳。',
  prereq: [], leadsTo: ['endgame', 'marvels', 'secret-invasion'],
  threads: ['shield', 'cosmic'], characters: ['惊奇队长', '卡罗尔·丹弗斯', '尼克·弗瑞', '斯克鲁人', '塔洛斯', '咕咕'],
  postCredits: 2, eggTip: '中段彩蛋:寻呼机信号中断,惊奇队长现身复仇者基地,直接接《复联4》。',
},
{
  id: 'endgame', title: '复仇者联盟4:终局之战', enTitle: 'Avengers: Endgame', type: 'movie', universe: 'mcu',
  phase: 3, release: '2019-04-26', chron: 230, storyYear: '2018→2023', runtime: 181, tier: 'core',
  rating: 8.4, emoji: '♾️',
  tagline: '「爱你三千遍。」十一年传奇的落幕。',
  synopsis: '响指五年后,幸存的复仇者靠蚁人带回的量子领域理论发起「时间劫案」,穿越回自己的过去偷取宝石。所有伏笔在最终之战集中引爆——传送门开启的那一刻,全球影院沸腾。',
  whyWatch: '无限传奇的句号,影史票房神话。「Avengers, assemble」终于喊出,托尼与队长各自走完弧光。看完这部,你会庆幸自己按顺序补完了前面二十一部。',
  prereq: ['infinity-war', 'ant-man-wasp', 'captain-marvel'], leadsTo: ['spider-man-2', 'wandavision', 'falcon-ws', 'loki-s1'],
  threads: ['avengers', 'stones', 'multiverse', 'asgard', 'cosmic', 'mystic'], characters: ['钢铁侠', '美国队长', '雷神', '浩克', '黑寡妇', '鹰眼', '蚁人', '惊奇队长', '灭霸', '涅布拉'],
  postCredits: 0, eggTip: '没有彩蛋,只有黑屏中一声打铁声——那是 2008 年托尼在山洞里敲下的第一锤。',
},
{
  id: 'spider-man-2', title: '蜘蛛侠:英雄远征', enTitle: 'Spider-Man: Far From Home', type: 'movie', universe: 'mcu',
  phase: 3, release: '2019-07-02', chron: 290, storyYear: '2024', runtime: 129, tier: 'core',
  rating: 7.4, emoji: '🗼',
  tagline: '后钢铁侠时代:谁来接班?',
  synopsis: '响指逆转后的世界努力回归日常,彼得只想在欧洲毕业旅行时向 MJ 表白,却被弗瑞抓去和「神秘客」并肩作战——一个用全息骗术把自己包装成英雄的顶级演员。',
  whyWatch: '无限传奇的正式收尾(官方划入第三阶段),处理整个世界对托尼的告别。片尾彩蛋直接引爆《英雄无归》:蜘蛛侠身份被全球曝光。',
  prereq: ['spider-man-1', 'endgame'], leadsTo: ['spider-man-3'],
  threads: ['spiderman', 'shield'], characters: ['蜘蛛侠', '彼得·帕克', '神秘客', 'MJ', '内德', '尼克·弗瑞', '快乐'],
  postCredits: 2, eggTip: '中段彩蛋蜘蛛侠身份曝光;片尾揭示弗瑞全片都是斯克鲁人塔洛斯假扮。',
},

/* ================= 第四阶段 ================= */
{
  id: 'wandavision', title: '旺达幻视', enTitle: 'WandaVision', type: 'series', universe: 'mcu',
  phase: 4, release: '2021-01-15', chron: 250, storyYear: '2023', runtime: 350, episodes: 9, tier: 'core',
  rating: 7.9, emoji: '📺',
  tagline: 'MCU 首部正剧:美式情景喜剧包裹的悲伤。',
  synopsis: '旺达与幻视在新泽西小镇过着黑白电视剧般的完美夫妻生活——可幻视明明已经死了。随着「剧集」画风逐年代演进,小镇之外的真相逐渐显形:这是一场用混沌魔法织成的巨大悲伤。',
  whyWatch: '迪士尼+时代的开山之作,把美剧史串成叙事诡计。旺达正式成为「绯红女巫」,直接铺垫《奇异博士2》;阿加莎也从这里走出自己的衍生剧。',
  prereq: ['aou', 'endgame'], leadsTo: ['mom', 'agatha'],
  threads: ['stones', 'mystic'], characters: ['绯红女巫', '旺达', '幻视', '阿加莎', '莫妮卡', '吉米·伍'],
  postCredits: 2, eggTip: '第9集有两个彩蛋:白幻视飞走 + 旺达魂体研读黑暗神书,听见双子呼救。',
},
{
  id: 'falcon-ws', title: '猎鹰与冬兵', enTitle: 'The Falcon and the Winter Soldier', type: 'series', universe: 'mcu',
  phase: 4, release: '2021-03-19', chron: 260, storyYear: '2023-2024', runtime: 300, episodes: 6, tier: 'recommended',
  rating: 7.1, emoji: '🪽',
  tagline: '盾牌太重:谁配当下一任美国队长?',
  synopsis: '山姆·威尔逊把盾牌上交国家,政府却火速任命了一位「官方美队」。山姆与巴基在追查恐怖组织「碎旗者」的过程中,直面血清、种族与国家象征的沉重议题。',
  whyWatch: '山姆接棒美国队长的完整心路,直通《美队4》。约翰·沃克(US Agent)与瓦伦蒂娜的招募暗线在《雷霆特攻队》开花结果。',
  prereq: ['cap-2', 'endgame'], leadsTo: ['brave-new-world', 'thunderbolts'],
  threads: ['newgen'], characters: ['猎鹰', '山姆·威尔逊', '冬兵', '巴基', '约翰·沃克', '泽莫男爵', '瓦伦蒂娜'],
  postCredits: 0, eggTip: '最终集片名变更为《美国队长与冬日战士》——正式交棒。',
},
{
  id: 'loki-s1', title: '洛基 第一季', enTitle: 'Loki Season 1', type: 'series', universe: 'mcu',
  phase: 4, release: '2021-06-09', chron: 240, storyYear: '时间之外', runtime: 280, episodes: 6, tier: 'core',
  rating: 8.2, emoji: '⏳',
  tagline: '多元宇宙传奇真正的起点。',
  synopsis: '《复联4》时间劫案中带着魔方逃跑的 2012 版洛基,被「时间变异管理局(TVA)」逮捕。他在追查另一个自己(西尔维)的过程中,揭开了神圣时间线尽头的秘密——以及「征服者」的存在。',
  whyWatch: '想看懂第四、五阶段,这部是绕不开的钥匙:TVA、时间分支、康的变体全部源于此。剧本与美术都是迪士尼+剧集的天花板。',
  prereq: ['endgame'], leadsTo: ['loki-s2', 'mom', 'deadpool-wolverine'],
  threads: ['multiverse', 'asgard'], characters: ['洛基', '西尔维', '莫比乌斯', '拉冯娜', '康', '残存者'],
  postCredits: 1, eggTip: '第1集彩蛋与第6集结尾:神圣时间线炸裂,雕像变成了康——多元宇宙就此失控。',
},
{
  id: 'what-if-s1', title: '假如…? 第一季', enTitle: 'What If...? Season 1', type: 'anim', universe: 'mcu',
  phase: 4, release: '2021-08-11', chron: null, storyYear: '多元宇宙', runtime: 280, episodes: 9, tier: 'optional',
  rating: 7.4, emoji: '🔮',
  tagline: '观察者视角:如果历史拐了个弯?',
  synopsis: '观察者尤塔图凝视多元宇宙的无数分支:如果卡特特工打了血清?如果特查拉成了星爵?如果奥创赢了?一集一个平行宇宙的脑洞动画。',
  whyWatch: '轻松的多元宇宙入门读物,卡特队长等变体后来在《奇异博士2》真人登场。单元剧结构,挑感兴趣的集数看也行。',
  prereq: ['loki-s1'], leadsTo: [],
  threads: ['multiverse'], characters: ['观察者', '卡特队长', '奇异博士至尊', '僵尸英雄'],
  postCredits: 0, eggTip: '「奇异博士至尊」一集是全季最佳,也是《奇异博士2》的精神前传。',
},
{
  id: 'shang-chi', title: '尚气与十环传奇', enTitle: 'Shang-Chi and the Legend of the Ten Rings', type: 'movie', universe: 'mcu',
  phase: 4, release: '2021-09-03', chron: 270, storyYear: '2024', runtime: 132, tier: 'recommended',
  rating: 7.4, emoji: '🐉',
  tagline: '漫威首位华裔英雄,武术设计一流。',
  synopsis: '旧金山泊车小弟尚气被父亲——执掌十环组织千年的文武——强行卷回家族恩怨。为守护母亲故乡塔罗村,他必须直面父亲、继承十环。',
  whyWatch: '梁朝伟贡献了 MCU 最有层次的反派之一,公交车打斗与竹林比武致敬港片美学。十环的能量来源之谜将连接未来剧情。',
  prereq: [], leadsTo: [],
  threads: [], characters: ['尚气', '文武', '夏灵', '凯蒂', '温蒂', '阿贝丝'],
  postCredits: 2, eggTip: '中段彩蛋:惊奇队长与班纳分析十环信号——它在向宇宙深处发送信标。',
},
{
  id: 'eternals', title: '永恒族', enTitle: 'Eternals', type: 'movie', universe: 'mcu',
  phase: 4, release: '2021-11-05', chron: 280, storyYear: '2024', runtime: 156, tier: 'optional',
  rating: 6.3, emoji: '🗿',
  tagline: '赵婷执导:七千年守望地球的神明。',
  synopsis: '十位永恒族成员七千年前受天神族派遣驻守地球,只杀变异异兽、不干涉人类纷争。当「大显灵」临近,他们才发现自己守护的其实是一场行星级的孵化仪式。',
  whyWatch: '格局最宏大也最游离于主线的一部,解释了天神族与地球的真正关系。口碑两极,但黑骑士与血刃的彩蛋是未来伏笔。',
  prereq: [], leadsTo: [],
  threads: [], characters: ['瑟西', '伊卡瑞斯', '瑟娜', '金戈', '菲斯托斯', '黑骑士'],
  postCredits: 2, eggTip: '中段彩蛋星狐与「饿虎」登场;片尾黑骑士拔出乌木刃,画外音来自刀锋战士。',
},
{
  id: 'spider-man-3', title: '蜘蛛侠:英雄无归', enTitle: 'Spider-Man: No Way Home', type: 'movie', universe: 'mcu',
  phase: 4, release: '2021-12-17', chron: 300, storyYear: '2024', runtime: 148, tier: 'core',
  rating: 8.2, emoji: '🕸️',
  tagline: '三代蜘蛛侠同框,情怀核弹。',
  synopsis: '身份曝光后的彼得生活崩塌,他请奇异博士施展遗忘咒术,结果咒语失控,把其他宇宙里认识彼得·帕克的人全部拽了过来——章鱼博士、绿魔、电光人,以及……另外两位蜘蛛侠。',
  whyWatch: '横跨二十年三个蜘蛛侠系列的世纪同框,把「能力越大责任越大」重新讲了一遍并讲到极致。看之前强烈建议补完雷米三部曲与超凡系列,泪点会翻倍。',
  prereq: ['spider-man-2', 'doctor-strange', 'raimi-1', 'raimi-2', 'raimi-3', 'tasm-1', 'tasm-2'], leadsTo: ['mom', 'brand-new-day'],
  threads: ['multiverse', 'spiderman', 'mystic'], characters: ['蜘蛛侠', '彼得·帕克', '奇异博士', '绿魔', '章鱼博士', '电光人', 'MJ', '内德', '梅姨'],
  postCredits: 2, eggTip: '中段彩蛋:毒液埃迪留下了一点共生体;片尾是《奇异博士2》预告。',
},
{
  id: 'mom', title: '奇异博士2:疯狂多元宇宙', enTitle: 'Doctor Strange in the Multiverse of Madness', type: 'movie', universe: 'mcu',
  phase: 4, release: '2022-05-06', chron: 310, storyYear: '2025', runtime: 126, tier: 'core',
  rating: 6.9, emoji: '🪞',
  tagline: '山姆·雷米执导:恐怖片质感的多元宇宙狂奔。',
  synopsis: '能穿梭多元宇宙的少女「美国队」被怪物追杀,求助于奇异博士。而追杀她的幕后黑手,竟是被黑暗神书腐蚀、只想夺回孩子的绯红女巫。一场横跨无数宇宙的追逃就此展开。',
  whyWatch: '《旺达幻视》的直接后续与旺达黑化的总爆发,「光照会」的惊人客串阵容与「入侵」概念都在本片抛出。看前务必补完《旺达幻视》,否则旺达的动机完全接不住。',
  prereq: ['doctor-strange', 'wandavision', 'spider-man-3', 'loki-s1'], leadsTo: ['agatha'],
  threads: ['multiverse', 'mystic'], characters: ['奇异博士', '绯红女巫', '旺达', '美国队', '王', '莫度', '克莉'],
  postCredits: 2, eggTip: '中段彩蛋:克莉邀请斯特兰奇进入黑暗维度;片尾是爆米花小哥的搞笑镜头。',
},
{
  id: 'hawkeye', title: '鹰眼', enTitle: 'Hawkeye', type: 'series', universe: 'mcu',
  phase: 4, release: '2021-11-24', chron: 305, storyYear: '2024圣诞', runtime: 300, episodes: 6, tier: 'recommended',
  rating: 7.5, emoji: '🏹',
  tagline: '圣诞档温情动作剧:新老鹰眼交接。',
  synopsis: '克林特只想赶在圣诞节前回家,却被狂热粉丝凯特·毕肖普卷入自己当「浪人」时期留下的烂账。金并浮出水面,黑寡妇的妹妹叶莲娜也带着账单找上门来。',
  whyWatch: '凯特·毕肖普是新生代最讨喜的角色之一,叶莲娜与金并的登场把网飞《夜魔侠》宇宙正式并入 MCU。轻快好看的圣诞小品。',
  prereq: ['endgame', 'black-widow'], leadsTo: ['echo'],
  threads: ['newgen'], characters: ['鹰眼', '凯特·毕肖普', '叶莲娜', '金并', '回声', '幸运狗'],
  postCredits: 0, eggTip: '最后一集的罗杰斯音乐剧完整版片段就是彩蛋本蛋。',
},
{
  id: 'black-widow', title: '黑寡妇', enTitle: 'Black Widow', type: 'movie', universe: 'mcu',
  phase: 4, release: '2021-07-09', chron: 160, storyYear: '2016', runtime: 134, tier: 'recommended',
  rating: 6.7, emoji: '⌛',
  tagline: '迟到的告别:娜塔莎的家庭往事。',
  synopsis: '时间回到《内战》之后:逃亡中的娜塔莎被迫与「妹妹」叶莲娜重聚,直捣制造黑寡妇的红房子,清算养父母与过去。一部迟到十年的单人电影。',
  whyWatch: '故事发生在内战与无限战争之间,为娜塔莎补上告别信。真正的遗产是叶莲娜——她将贯穿《鹰眼》与《雷霆特攻队》。',
  prereq: ['civil-war'], leadsTo: ['hawkeye', 'thunderbolts'],
  threads: ['newgen'], characters: ['黑寡妇', '娜塔莎', '叶莲娜', '红色守卫者', '梅琳娜', '模仿大师'],
  postCredits: 1, eggTip: '片尾叶莲娜扫墓,瓦伦蒂娜现身派活:目标——鹰眼。直接接《鹰眼》剧集。',
},
{
  id: 'moon-knight', title: '月光骑士', enTitle: 'Moon Knight', type: 'series', universe: 'mcu',
  phase: 4, release: '2022-03-30', chron: 330, storyYear: '2025', runtime: 280, episodes: 6, tier: 'optional',
  rating: 7.3, emoji: '🌙',
  tagline: '人格分裂+埃及神话,独立成篇。',
  synopsis: '博物馆礼品店员工史蒂文发现自己身体里住着雇佣兵马克·斯佩克特——以及月神孔苏的战衣。两个(或更多?)人格必须合作,阻止狂信徒释放女神阿米特。',
  whyWatch: '奥斯卡·伊萨克一人分饰多角的表演盛宴,与主线几乎零关联,当独立惊悚剧看即可。',
  prereq: [], leadsTo: [],
  threads: [], characters: ['月光骑士', '马克·斯佩克特', '史蒂文', '孔苏', '莱拉', '哈罗'],
  postCredits: 1, eggTip: '最终集彩蛋揭示第三人格「杰克·洛克利」——疯狂程度更上一层。',
},
{
  id: 'ms-marvel', title: '惊奇少女', enTitle: 'Ms. Marvel', type: 'series', universe: 'mcu',
  phase: 4, release: '2022-06-08', chron: 350, storyYear: '2025', runtime: 270, episodes: 6, tier: 'optional',
  rating: 6.2, emoji: '✨',
  tagline: '惊奇队长头号迷妹的超能力青春剧。',
  synopsis: '新泽西的巴基斯坦裔高中生卡玛拉是惊奇队长的狂热粉丝,一只神秘手镯唤醒了她体内的光能。青春烦恼、家族历史与超能力觉醒交织。',
  whyWatch: '《惊奇队长2》的直接前置,卡玛拉的手镯与「变种人」一词的首次出现都埋在这里。风格清新,青春片质感。',
  prereq: ['captain-marvel'], leadsTo: ['marvels'],
  threads: ['cosmic'], characters: ['惊奇少女', '卡玛拉·汗', '布鲁诺', '娜琪亚'],
  postCredits: 1, eggTip: '最终集彩蛋:卡玛拉的手镯发光,惊奇队长突然出现在她房间——《惊奇队长2》开场。',
},
{
  id: 'thor-lt', title: '雷神4:爱与雷霆', enTitle: 'Thor: Love and Thunder', type: 'movie', universe: 'mcu',
  phase: 4, release: '2022-07-08', chron: 360, storyYear: '2025', runtime: 118, tier: 'optional',
  rating: 6.2, emoji: '🐐',
  tagline: '简·福斯特举起雷神之锤。',
  synopsis: '「屠神者」格尔立誓杀尽诸神,索尔重整旗鼓迎战,却发现前女友简·福斯特举起了重铸的雷神之锤——以及她藏起来的病情。',
  whyWatch: '延续《雷神3》的喜剧路线但口碑下滑,简·福斯特线的结局与「雷神之女」的登场是主要看点。可按兴趣选看。',
  prereq: ['thor-ragnarok', 'endgame'], leadsTo: [],
  threads: ['asgard', 'cosmic'], characters: ['雷神', '简·福斯特', '女武神', '屠神者格尔', '宙斯', '科尔格'],
  postCredits: 2, eggTip: '中段彩蛋:宙斯之子海格力斯领命复仇;片尾简在英灵殿受海姆达尔迎接。',
},
{
  id: 'she-hulk', title: '女浩克', enTitle: 'She-Hulk: Attorney at Law', type: 'series', universe: 'mcu',
  phase: 4, release: '2022-08-18', chron: 340, storyYear: '2025', runtime: 300, episodes: 9, tier: 'optional',
  rating: 5.3, emoji: '⚖️',
  tagline: '打破第四面墙的超英律政喜剧。',
  synopsis: '律师珍妮弗因表哥布鲁斯·班纳的血液意外获得浩克化能力,一边打理「超人类法律部」的奇葩案件,一边应付变绿后的社交生活,时不时还直接跟观众唠两句。',
  whyWatch: '争议很大的一部,但夜魔侠在此回归 MCU 并与主角谈起恋爱,大结局的第四面墙玩法极其大胆。追求全收集再看。',
  prereq: [], leadsTo: ['daredevil-ba'],
  threads: [], characters: ['女浩克', '珍妮弗', '浩克', '夜魔侠', '泰坦妮亚', '憎恶'],
  postCredits: 0, eggTip: '大结局直接闯入漫威制片流程页面吐槽编剧——超英剧史上头一遭。',
},
{
  id: 'werewolf', title: '暗夜狼人', enTitle: 'Werewolf by Night', type: 'special', universe: 'mcu',
  phase: 4, release: '2022-10-07', chron: 370, storyYear: '2025', runtime: 53, tier: 'optional',
  rating: 7.3, emoji: '🐺',
  tagline: '黑白老式恐怖片致敬,50 分钟特别篇。',
  synopsis: '怪物猎人们齐聚布拉德通道,争夺血石继承权,猎物却是传说中的怪物「曼-辛」。猎人杰克·拉塞尔身上也藏着一个月圆之夜的秘密。',
  whyWatch: 'MCU 首部「特别呈现」,黑白摄影+实体特效致敬环球老恐怖片,独立成篇,一顿饭的时间就能看完。',
  prereq: [], leadsTo: [],
  threads: [], characters: ['暗夜狼人', '杰克·拉塞尔', '爱尔莎', '曼-辛'],
  postCredits: 1, eggTip: '怪物英雄「曼-辛」泰德是漫威恐怖漫画的活化石。',
},
{
  id: 'wakanda-forever', title: '黑豹2:瓦坎达万岁', enTitle: 'Black Panther: Wakanda Forever', type: 'movie', universe: 'mcu',
  phase: 4, release: '2022-11-11', chron: 380, storyYear: '2025', runtime: 161, tier: 'recommended',
  rating: 6.7, emoji: '🌊',
  tagline: '献给查德维克·博斯曼的挽歌。',
  synopsis: '特查拉国王病逝(呼应主演博斯曼离世),瓦坎达在悲痛中直面列强觊觎。海底王国塔洛坎的王者纳摩浮出水面,苏睿必须在复仇与传承之间做出选择。',
  whyWatch: '真挚的告别之作,纳摩是第四阶段最有分量的新角色。天才少女「钢铁之心」莉莉在此登场,衔接其个人剧集。',
  prereq: ['black-panther'], leadsTo: ['ironheart'],
  threads: ['newgen'], characters: ['苏睿', '纳摩', '奥科耶', '拉玛达王太后', '钢铁之心', '姆巴库'],
  postCredits: 1, eggTip: '中段彩蛋:苏睿在海边烧掉丧服,娜奇雅牵出一个男孩——特查拉的儿子。',
},
{
  id: 'holiday-special', title: '银河护卫队:圣诞特别篇', enTitle: 'The Guardians of the Galaxy Holiday Special', type: 'special', universe: 'mcu',
  phase: 4, release: '2022-11-25', chron: 390, storyYear: '2025圣诞', runtime: 44, tier: 'optional',
  rating: 7.0, emoji: '🎄',
  tagline: '为了哄星爵开心,绑架一个地球明星。',
  synopsis: '为了治愈星爵的圣诞抑郁,德拉克斯与螳螂女溜到地球,绑来了他童年偶像凯文·贝肯本人。一部无厘头的太空圣诞贺岁片。',
  whyWatch: '45 分钟的纯快乐,同时交代了一个《银护3》的重要前情:螳螂女与星爵的真实关系。',
  prereq: ['gotg2'], leadsTo: ['gotg3'],
  threads: ['cosmic'], characters: ['星爵', '德拉克斯', '螳螂女', '火箭浣熊', '凯文·贝肯'],
  postCredits: 1, eggTip: '格鲁特织毛衣。就这,但很可爱。',
},

/* ================= 第五阶段 ================= */
{
  id: 'quantumania', title: '蚁人3:量子狂潮', enTitle: 'Ant-Man and the Wasp: Quantumania', type: 'movie', universe: 'mcu',
  phase: 5, release: '2023-02-17', chron: 400, storyYear: '2026', runtime: 124, tier: 'recommended',
  rating: 6.1, emoji: '⚛️',
  tagline: '征服者康正式亮相大银幕。',
  synopsis: '斯科特一家被吸入量子领域,发现这里不仅是微观世界,更是一个流亡帝国——被放逐的「征服者康」正在此重建战力,等待逃出生天的那一刻。',
  whyWatch: '多元宇宙传奇原定大反派康的电影首秀(乔纳森·梅杰斯饰),《洛基》看完再看体验更佳。正片口碑一般,但康的戏份值回票价。',
  prereq: ['ant-man-wasp', 'loki-s1'], leadsTo: ['doomsday'],
  threads: ['multiverse'], characters: ['蚁人', '黄蜂女', '凯茜', '征服者康', '莫多克', '皮姆博士', '珍妮特'],
  postCredits: 2, eggTip: '中段彩蛋:无数康的变体齐聚议会;片尾彩蛋是《洛基》第二季片段。',
},
{
  id: 'gotg3', title: '银河护卫队3', enTitle: 'Guardians of the Galaxy Vol. 3', type: 'movie', universe: 'mcu',
  phase: 5, release: '2023-05-05', chron: 410, storyYear: '2026', runtime: 150, tier: 'core',
  rating: 7.9, emoji: '🦝',
  tagline: '火箭的身世,银护的谢幕。',
  synopsis: '亚当·术士突袭「无处」重创火箭,救他的唯一办法是闯入其创造者「至高进化」的实验室。火箭浣熊的黑暗身世首次揭开——这一次,护卫队为家人而战。',
  whyWatch: '詹姆斯·古恩三部曲的完美收官,火箭的往事是全系列最重的情感锤。初代银河护卫队在此正式解散,泪腺弱者请备纸巾。',
  prereq: ['gotg2', 'endgame', 'holiday-special'], leadsTo: [],
  threads: ['cosmic'], characters: ['星爵', '火箭浣熊', '格鲁特', '涅布拉', '德拉克斯', '螳螂女', '卡魔拉', '至高进化', '亚当·术士'],
  postCredits: 2, eggTip: '片尾彩蛋:新一代银河护卫队亮相,字幕写着「传奇的星爵将会回归」。',
},
{
  id: 'secret-invasion', title: '秘密入侵', enTitle: 'Secret Invasion', type: 'series', universe: 'mcu',
  phase: 5, release: '2023-06-21', chron: 420, storyYear: '2026', runtime: 280, episodes: 6, tier: 'optional',
  rating: 5.9, emoji: '🦎',
  tagline: '弗瑞的谍战剧:身边人还能信谁?',
  synopsis: '三十年前弗瑞承诺帮斯克鲁人寻找新家园,承诺落空后,激进派斯克鲁人渗透各国高层,策划夺取地球。年迈的弗瑞不带超级英雄,独自下场清理门户。',
  whyWatch: '设定承接《惊奇队长》,揭示「谁可能一直是斯克鲁人」。成片口碑不佳,可只看首尾两集了解关键信息:罗德斯的身份与超级斯克鲁人的诞生。',
  prereq: ['captain-marvel', 'spider-man-2'], leadsTo: ['marvels'],
  threads: ['shield'], characters: ['尼克·弗瑞', '塔洛斯', '格拉维克', '希尔', '罗德斯', '拉不邦'],
  postCredits: 0, eggTip: '大结局揭晓超级斯克鲁人融合了复仇者的 DNA——包括惊奇队长。',
},
{
  id: 'loki-s2', title: '洛基 第二季', enTitle: 'Loki Season 2', type: 'series', universe: 'mcu',
  phase: 5, release: '2023-10-05', chron: 430, storyYear: '时间之外', runtime: 280, episodes: 6, tier: 'core',
  rating: 8.2, emoji: '⏰',
  tagline: '「我知道我想成为怎样的神了。」',
  synopsis: '神圣时间线炸裂成无数分支,时间织机濒临过载,TVA 面临崩溃。洛基在时间中不断「滑移」,为了拯救所有朋友和所有时间线,他走向了自己的王座——以千年孤独为代价。',
  whyWatch: '洛基十二年角色弧光的终点,结局被誉为 MCU 剧集最佳。他成为「故事之神」支撑起多元宇宙之树,这一设定将直通《毁灭日》与《秘密战争》。',
  prereq: ['loki-s1'], leadsTo: ['deadpool-wolverine', 'doomsday'],
  threads: ['multiverse', 'asgard'], characters: ['洛基', '西尔维', '莫比乌斯', 'OB', '维克多·泰姆利', '拉冯娜'],
  postCredits: 0, eggTip: '结尾洛基坐上时间之树王座的长镜头,建议静音手机认真看完。',
},
{
  id: 'what-if-s2', title: '假如…? 第二季', enTitle: 'What If...? Season 2', type: 'anim', universe: 'mcu',
  phase: 5, release: '2023-12-22', chron: null, storyYear: '多元宇宙', runtime: 270, episodes: 9, tier: 'optional',
  rating: 7.0, emoji: '🎲',
  tagline: '多元宇宙脑洞第二弹。',
  synopsis: '观察者继续巡游:海拉与十环、1602 年的复仇者、圣诞夜的快乐·霍根大战大盗……卡特队长再次成为贯穿线索。',
  whyWatch: '娱乐性优先的单元动画,与主线关联不大,当甜点吃。',
  prereq: ['what-if-s1'], leadsTo: [],
  threads: ['multiverse'], characters: ['观察者', '卡特队长', '海拉', '快乐·霍根'],
  postCredits: 0, eggTip: '「1602」一集改编自尼尔·盖曼的同名神作漫画。',
},
{
  id: 'echo', title: '回声', enTitle: 'Echo', type: 'series', universe: 'mcu',
  phase: 5, release: '2024-01-09', chron: 450, storyYear: '2026', runtime: 230, episodes: 5, tier: 'optional',
  rating: 6.3, emoji: '🪶',
  tagline: '金并养女的暗黑寻根之旅。',
  synopsis: '《鹰眼》中枪击金并后,聋哑杀手玛雅逃回俄克拉荷马老家,在乔克托族血脉的祖灵召唤中重新认识自己,并与「叔叔」金并做个了断。',
  whyWatch: 'MCU 首部 TV-MA 分级剧集,风格冷硬。主要价值是延续金并的故事线,通往《夜魔侠:重生》。',
  prereq: ['hawkeye'], leadsTo: ['daredevil-ba'],
  threads: ['newgen'], characters: ['回声', '玛雅', '金并', '夜魔侠'],
  postCredits: 0, eggTip: '第1集夜魔侠客串,与玛雅有一场高质量近身战。',
},
{
  id: 'marvels', title: '惊奇队长2', enTitle: 'The Marvels', type: 'movie', universe: 'mcu',
  phase: 5, release: '2023-11-10', chron: 440, storyYear: '2026', runtime: 105, tier: 'optional',
  rating: 5.6, emoji: '💫',
  tagline: '三位光系英雄的量子纠缠。',
  synopsis: '惊奇队长、惊奇少女与莫妮卡三人的光系能力发生量子纠缠,一用能力就互相换位。三人被迫组队,对抗撕开空间跳跃点的克里叛军首领达尔-班。',
  whyWatch: '票房口碑双失利,但片尾彩蛋分量极重:莫妮卡被困的平行宇宙里出现了 X 战警的光束眼与「X 教授式」大反派铺垫。',
  prereq: ['captain-marvel', 'ms-marvel', 'secret-invasion'], leadsTo: ['doomsday'],
  threads: ['cosmic', 'shield'], characters: ['惊奇队长', '惊奇少女', '莫妮卡', '达尔-班', '尼克·弗瑞', '咕咕'],
  postCredits: 1, eggTip: '片尾彩蛋:莫妮卡在平行宇宙醒来,病床边坐着「光束」——X战警正式叩门 MCU。',
},
{
  id: 'deadpool-wolverine', title: '死侍与金刚狼', enTitle: 'Deadpool & Wolverine', type: 'movie', universe: 'mcu',
  phase: 5, release: '2024-07-26', chron: 460, storyYear: '2024', runtime: 128, tier: 'core',
  rating: 7.6, emoji: '🗡️',
  tagline: '贱贱正式进入 MCU,R 级情怀狂欢。',
  synopsis: '死侍的宇宙因金刚狼之死而濒临「时间线安乐死」,TVA 找上门来。为拯救家园,韦德横跨多元宇宙拉来一个「最差劲的金刚狼」,两人在虚空中杀出一条血路。',
  whyWatch: '福斯二十年漫威电影的告别典礼:无数前代角色返场,吐槽密度爆炸。建议先补《死侍》1、2 与《金刚狼3:殊死一战》,泪点与笑点都会翻倍。',
  prereq: ['deadpool-1', 'deadpool-2', 'logan', 'loki-s1'], leadsTo: ['doomsday'],
  threads: ['multiverse'], characters: ['死侍', '韦德', '金刚狼', '罗根', '卡桑德拉', 'TVA', '女死侍'],
  postCredits: 1, eggTip: '片尾用福斯时期珍贵片场花絮向二十年漫威福斯宇宙告别,泪目预警。',
},
{
  id: 'agatha', title: '阿加莎', enTitle: 'Agatha All Along', type: 'series', universe: 'mcu',
  phase: 5, release: '2024-09-18', chron: 470, storyYear: '2026', runtime: 320, episodes: 9, tier: 'optional',
  rating: 7.3, emoji: '🧹',
  tagline: '女巫之路:旺达幻视的暗黑姊妹篇。',
  synopsis: '失去力量的阿加莎召集一支草台女巫团,踏上传说中的「女巫之路」寻回魔力。而那个神秘的「少年」的真实身份,与旺达的双子有着直接关联。',
  whyWatch: '《旺达幻视》的直系续篇,揭晓比利(威斯坦)的下落,为「青年复仇者」拼上关键一块。歌曲《The Ballad of the Witches\' Road》直接参与叙事诡计。',
  prereq: ['wandavision'], leadsTo: [],
  threads: ['mystic'], characters: ['阿加莎', '比利', '威斯坦', '莉莉亚', '珍妮弗', '死亡女神'],
  postCredits: 0, eggTip: '中段大反转集《Familiar by Thy Side》被普遍认为是年度最佳单集。',
},
{
  id: 'what-if-s3', title: '假如…? 第三季', enTitle: 'What If...? Season 3', type: 'anim', universe: 'mcu',
  phase: 5, release: '2024-12-22', chron: null, storyYear: '多元宇宙', runtime: 240, episodes: 8, tier: 'optional',
  rating: 6.8, emoji: '🃏',
  tagline: '观察者的最终季。',
  synopsis: '《假如…?》最终季:机甲复仇者、西部世界1872、观察者本人接受审判。多元宇宙动画实验的收官。',
  whyWatch: '系列完结篇,完成观察者自身的角色弧光。选看即可。',
  prereq: ['what-if-s2'], leadsTo: [],
  threads: ['multiverse'], characters: ['观察者', '卡特队长', '尚气', '暴风女'],
  postCredits: 0, eggTip: '最终集观察者的选择呼应第一季结尾的誓言。',
},
{
  id: 'daredevil-ba', title: '夜魔侠:重生', enTitle: 'Daredevil: Born Again', type: 'series', universe: 'mcu',
  phase: 5, release: '2025-03-04', chron: 480, storyYear: '2026-2027', runtime: 400, episodes: 9, tier: 'recommended',
  rating: 8.2, emoji: '😈',
  tagline: '网飞神剧正统续作:金并当上了市长。',
  synopsis: '好友枪手之死让马特·默多克封印夜魔侠身份,专心做律师;与此同时,金并竞选纽约市长成功,整座城市滑向合法化的黑暗。两人的「君子协定」注定破裂。',
  whyWatch: '网飞《夜魔侠》三季的直接续篇,暴力水准与表演全面在线。建议先补网飞版(至少第一、三季),人物关系才吃得透。',
  prereq: ['dd-netflix', 'echo'], leadsTo: [],
  threads: ['newgen'], characters: ['夜魔侠', '马特·默多克', '金并', '惩罚者', '白虎', '子弹眼'],
  postCredits: 0, eggTip: '第1集的震撼开场十分钟,网飞老粉请系好安全带。',
},
{
  id: 'brave-new-world', title: '美国队长4:美丽新世界', enTitle: 'Captain America: Brave New World', type: 'movie', universe: 'mcu',
  phase: 5, release: '2025-02-14', chron: 490, storyYear: '2027', runtime: 118, tier: 'recommended',
  rating: 5.9, emoji: '🦅',
  tagline: '山姆的首战:红浩克总统。',
  synopsis: '山姆·威尔逊以美国队长身份出席罗斯总统的天神岛条约谈判,却卷入一场针对总统的操控阴谋。当罗斯在白宫前变身红浩克,山姆必须证明无血清者也配得上盾牌。',
  whyWatch: '山姆版美队的首部电影,收束《无敌浩克》《永恒族》(天神岛)等多条旧线。口碑平平,但对理解新复仇者阵容的政治格局有用。',
  prereq: ['falcon-ws', 'hulk', 'eternals'], leadsTo: ['doomsday'],
  threads: ['avengers', 'newgen'], characters: ['美国队长', '山姆·威尔逊', '罗斯总统', '红浩克', '猎鹰(华金)', '塞缪尔·斯特恩斯'],
  postCredits: 1, eggTip: '片尾斯特恩斯狱中警告山姆:多元宇宙的「其他世界」正在到来。',
},
{
  id: 'thunderbolts', title: '雷霆特攻队*', enTitle: 'Thunderbolts*', type: 'movie', universe: 'mcu',
  phase: 5, release: '2025-05-02', chron: 500, storyYear: '2027', runtime: 127, tier: 'core',
  rating: 7.3, emoji: '🖤',
  tagline: '一群反英雄接住了彼此,片名的 * 有玄机。',
  synopsis: '叶莲娜、红色守卫者、幽灵、US Agent 等一票「二线反英雄」被瓦伦蒂娜设局灭口,阴差阳错救出实验体「哨兵」——一个拥有超人力量、内心却住着「虚空」的抑郁症患者。',
  whyWatch: '第五阶段口碑最佳的电影之一,把抑郁与自我救赎拍进超英框架。片尾正式改名「新复仇者」,直通《毁灭日》。',
  prereq: ['black-widow', 'falcon-ws', 'hawkeye'], leadsTo: ['doomsday'],
  threads: ['avengers', 'newgen'], characters: ['叶莲娜', '哨兵', '鲍勃', '红色守卫者', '幽灵', 'US Agent', '瓦伦蒂娜', '冬兵'],
  postCredits: 2, eggTip: '片尾彩蛋:神奇四侠的飞船正穿越到本宇宙——第六阶段开幕。',
},
{
  id: 'ironheart', title: '钢铁之心', enTitle: 'Ironheart', type: 'series', universe: 'mcu',
  phase: 5, release: '2025-06-24', chron: 505, storyYear: '2027', runtime: 270, episodes: 6, tier: 'optional',
  rating: 5.5, emoji: '💠',
  tagline: '天才少女的装甲,与恶魔的交易。',
  synopsis: '从瓦坎达回到芝加哥的莉莉·威廉姆斯为造装甲不择手段,与神秘的「至尊帕克」帮派勾结——而对方的力量来源并非科技,而是魔法,背后站着恶魔墨菲斯托。',
  whyWatch: '钢铁侠精神续作+魔法侧大反派墨菲斯托的正式登场(粉丝催了五年的角色)。剧集本身口碑一般,按需选看。',
  prereq: ['wakanda-forever'], leadsTo: [],
  threads: ['newgen', 'mystic'], characters: ['钢铁之心', '莉莉', '至尊帕克', '墨菲斯托', 'N.A.T.A.L.I.E.'],
  postCredits: 1, eggTip: '大结局墨菲斯托现身,漫威终于兑现了这张藏了多年的牌。',
},
{
  id: 'eyes-of-wakanda', title: '瓦坎达之眼', enTitle: 'Eyes of Wakanda', type: 'anim', universe: 'mcu',
  phase: 5, release: '2025-08-06', chron: null, storyYear: '历史各时期', runtime: 120, episodes: 4, tier: 'optional',
  rating: 6.5, emoji: '👁️',
  tagline: '瓦坎达战士的千年秘史。',
  synopsis: '动画单元剧:历代瓦坎达「猎犬」特工在历史长河中追回流失振金的故事,横跨古代到近代。',
  whyWatch: '黑豹世界观的补充设定集,画风精美,体量很小。',
  prereq: ['black-panther'], leadsTo: [],
  threads: [], characters: ['瓦坎达战士', '猎犬特工'],
  postCredits: 0, eggTip: '注意历代「眼睛」与主线电影道具的呼应。',
},
{
  id: 'marvel-zombies', title: '漫威僵尸', enTitle: 'Marvel Zombies', type: 'anim', universe: 'mcu',
  phase: 5, release: '2025-09-24', chron: null, storyYear: '多元宇宙', runtime: 130, episodes: 4, tier: 'optional',
  rating: 6.6, emoji: '🧟',
  tagline: '尸变宇宙:R 级动画番外。',
  synopsis: '延续《假如…?》僵尸单集的平行宇宙:量子病毒吞噬地球,幸存的年轻英雄们在尸潮中护送「希望」。',
  whyWatch: 'MCU 首部 R 级动画,爽快猎奇向番外,与主线无关。',
  prereq: ['what-if-s1'], leadsTo: [],
  threads: ['multiverse'], characters: ['惊奇少女', '刀锋骑士', '斯派克', '僵尸绯红女巫'],
  postCredits: 0, eggTip: '僵尸绯红女巫的设定直接来自《假如…?》第一季名场面。',
},
{
  id: 'wonder-man', title: '神奇男侠', enTitle: 'Wonder Man', type: 'series', universe: 'mcu',
  phase: 5, release: '2026-01-27', chron: 515, storyYear: '2027', runtime: 240, episodes: 8, tier: 'optional',
  rating: 6.9, emoji: '🎬',
  tagline: '好莱坞讽刺喜剧:超英选秀现场。',
  synopsis: '拥有离子能力的落魄演员西蒙·威廉姆斯参加「神奇男侠」重启版试镜,一部把镜头对准超英产业本身的行业讽刺剧。',
  whyWatch: '漫威自嘲之作,本·金斯利的「冒牌满大人」回归。轻量选看。',
  prereq: [], leadsTo: [],
  threads: [], characters: ['神奇男侠', '西蒙·威廉姆斯', '特雷弗'],
  postCredits: 0, eggTip: '留意各种漫威影业的自黑梗。',
},

/* ================= 第六阶段 ================= */
{
  id: 'fantastic-four', title: '神奇四侠:初露锋芒', enTitle: 'The Fantastic Four: First Steps', type: 'movie', universe: 'mcu',
  phase: 6, release: '2025-07-25', chron: 520, storyYear: '1960s(828宇宙)', runtime: 115, tier: 'core',
  rating: 7.2, emoji: '4️⃣',
  tagline: '第一家庭终于回家,复古未来主义美学。',
  synopsis: '在复古未来风的地球-828,神奇四侠早已是家喻户晓的守护者。当吞星的先驱银影侠宣告地球死刑,里德与苏必须在拯救世界与保护新生儿之间做出不可能的选择。',
  whyWatch: '漫威「第一家庭」正式并入 MCU 版图,自成一个宇宙的复古美学广受好评。他们将在《毁灭日》与主宇宙汇合,是第六阶段的核心前置。',
  prereq: [], leadsTo: ['doomsday'],
  threads: ['multiverse'], characters: ['神奇先生', '隐形女', '霹雳火', '石头人', '银影侠', '吞星', '富兰克林'],
  postCredits: 2, eggTip: '中段彩蛋:四年后,富兰克林面前站着一个披斗篷的身影——毁灭博士。',
},
{
  id: 'brand-new-day', title: '蜘蛛侠:崭新的一天', enTitle: 'Spider-Man: Brand New Day', type: 'movie', universe: 'mcu',
  phase: 6, release: '2026-07-31', chron: 540, storyYear: '2027', runtime: 130, tier: 'core', upcoming: true,
  rating: 0, emoji: '🎒',
  tagline: '被全世界遗忘之后,彼得的新生活。',
  synopsis: '《英雄无归》咒语之后,无人记得彼得·帕克。孤身一人的蜘蛛侠回归街头,面对全新的敌人(据报包括憎恶与「疤面」),并与惩罚者产生交集。',
  whyWatch: '荷兰弟蜘蛛侠第四部,回归街头小人物路线。档期与内容以官方公布为准。',
  prereq: ['spider-man-3'], leadsTo: ['doomsday'],
  threads: ['spiderman'], characters: ['蜘蛛侠', '彼得·帕克', '惩罚者', '憎恶'],
  postCredits: null, eggTip: '上映后再来解锁。',
},
{
  id: 'doomsday', title: '复仇者联盟:毁灭日', enTitle: 'Avengers: Doomsday', type: 'movie', universe: 'mcu',
  phase: 6, release: '2026-12-18', chron: 550, storyYear: '???', runtime: 0, tier: 'core', upcoming: true,
  rating: 0, emoji: '🎭',
  tagline: '小罗伯特·唐尼回归——但这次是毁灭博士。',
  synopsis: '新复仇者、神奇四侠、雷霆战队与归来的旧日英雄将共同面对毁灭博士(小罗伯特·唐尼饰)。多元宇宙传奇的决战前夜。',
  whyWatch: '整个多元宇宙传奇收束的起点,《秘密战争》的上篇。此前的核心路线都是为这一战做准备。',
  prereq: ['thunderbolts', 'fantastic-four', 'loki-s2', 'deadpool-wolverine'], leadsTo: ['secret-wars'],
  threads: ['avengers', 'multiverse'], characters: ['毁灭博士', '新复仇者', '神奇四侠', 'X战警', '雷神', '奇异博士'],
  postCredits: null, eggTip: '上映后再来解锁。',
},
{
  id: 'secret-wars', title: '复仇者联盟:秘密战争', enTitle: 'Avengers: Secret Wars', type: 'movie', universe: 'mcu',
  phase: 6, release: '2027-12-17', chron: 560, storyYear: '???', runtime: 0, tier: 'core', upcoming: true,
  rating: 0, emoji: '🪐',
  tagline: '多元宇宙传奇的最终章。',
  synopsis: '改编自漫威史上最大事件之一《秘密战争》:当所有宇宙走向湮灭,幸存者将在「战场世界」为存续而战。传闻这将是 MCU 的一次重启节点。',
  whyWatch: '两代传奇的总决算。看到这里,你就是全勤观众了。',
  prereq: ['doomsday'], leadsTo: [],
  threads: ['avengers', 'multiverse'], characters: ['毁灭博士', '复仇者', '全员'],
  postCredits: null, eggTip: '上映后再来解锁。',
},

/* ================= 前代与番外:蜘蛛侠 ================= */
{
  id: 'raimi-1', title: '蜘蛛侠', enTitle: 'Spider-Man (2002)', type: 'movie', universe: 'raimi',
  phase: 0, release: '2002-05-03', chron: null, storyYear: null, runtime: 121, tier: 'recommended',
  rating: 7.4, emoji: '🕷️',
  tagline: '托比版初代:超英电影黄金时代的开端。',
  synopsis: '高中生彼得·帕克被变异蜘蛛咬伤获得超能力,在本叔之死中学会「能力越大,责任越大」,并与挚友之父——绿魔——展开宿命对决。',
  whyWatch: '现代超英电影的奠基之作。《英雄无归》的情怀核弹有一半引线埋在这里:绿魔、托比版彼得都将在那里回归。',
  prereq: [], leadsTo: ['raimi-2', 'spider-man-3'],
  threads: [], characters: ['蜘蛛侠(托比)', '绿魔', '玛丽·简', '哈里'],
  postCredits: 0, eggTip: '「能力越大,责任越大」的出处,后来被 MCU 反复致敬。',
},
{
  id: 'raimi-2', title: '蜘蛛侠2', enTitle: 'Spider-Man 2 (2004)', type: 'movie', universe: 'raimi',
  phase: 0, release: '2004-06-30', chron: null, storyYear: null, runtime: 127, tier: 'recommended',
  rating: 7.5, emoji: '🐙',
  tagline: '公认影史最佳超英电影候选。',
  synopsis: '彼得在生活重压下能力时灵时不灵,一度弃盾……弃衣而去。章鱼博士的悲剧与列车救援名场面,把「平凡人英雄」拍到极致。',
  whyWatch: '章鱼博士是《英雄无归》的核心回归角色,本片是他全部人物弧光的来源。列车戏至今仍是超英片天花板级调度。',
  prereq: ['raimi-1'], leadsTo: ['raimi-3', 'spider-man-3'],
  threads: [], characters: ['蜘蛛侠(托比)', '章鱼博士', '奥托', '玛丽·简', '哈里'],
  postCredits: 0, eggTip: '「他只是个孩子」——列车乘客保护昏迷蜘蛛侠的一幕,二十年后依然催泪。',
},
{
  id: 'raimi-3', title: '蜘蛛侠3', enTitle: 'Spider-Man 3 (2007)', type: 'movie', universe: 'raimi',
  phase: 0, release: '2007-05-04', chron: null, storyYear: null, runtime: 139, tier: 'optional',
  rating: 6.3, emoji: '🖤',
  tagline: '黑化彼得的社会性死亡现场。',
  synopsis: '共生体让彼得穿上黑衣、性格骤变,沙人与新绿魔两线夹击。三反派塞车导致口碑滑坡,但「邪恶彼得舞」意外成为互联网永恒梗图。',
  whyWatch: '沙人在《英雄无归》回归;托比黑化跳舞的梗你迟早会在网上刷到,不如先看正片。',
  prereq: ['raimi-2'], leadsTo: ['spider-man-3'],
  threads: [], characters: ['蜘蛛侠(托比)', '沙人', '毒液', '哈里', '玛丽·简'],
  postCredits: 0, eggTip: '那段黑化街舞,请务必怀着敬畏之心观看。',
},
{
  id: 'tasm-1', title: '超凡蜘蛛侠', enTitle: 'The Amazing Spider-Man', type: 'movie', universe: 'tasm',
  phase: 0, release: '2012-07-03', chron: null, storyYear: null, runtime: 136, tier: 'optional',
  rating: 6.9, emoji: '🦎',
  tagline: '加菲版蜘蛛侠:最帅的彼得·帕克。',
  synopsis: '重启版起源:滑板少年彼得追查父母失踪之谜,与康纳斯博士(蜥蜴人)对决,并与格温·斯黛西相恋。',
  whyWatch: '加菲版彼得在《英雄无归》的回归是全片最大泪点之一——他接住了那个「没接住」的遗憾。为了那一幕,值得补完这两部。',
  prereq: [], leadsTo: ['tasm-2', 'spider-man-3'],
  threads: [], characters: ['蜘蛛侠(加菲)', '格温', '蜥蜴人'],
  postCredits: 1, eggTip: '格温与彼得的化学反应来自演员的真实恋情。',
},
{
  id: 'tasm-2', title: '超凡蜘蛛侠2', enTitle: 'The Amazing Spider-Man 2', type: 'movie', universe: 'tasm',
  phase: 0, release: '2014-05-02', chron: null, storyYear: null, runtime: 142, tier: 'optional',
  rating: 6.6, emoji: '🔌',
  tagline: '那个没能接住的瞬间。',
  synopsis: '彼得与格温在毕业季的爱情,被电光人与新绿魔的双重威胁撕碎。钟楼一幕成为系列最痛的记忆,也是《英雄无归》救赎戏的源头。',
  whyWatch: '电光人在《英雄无归》回归;结局的钟楼戏是理解加菲版彼得心结的必修课。',
  prereq: ['tasm-1'], leadsTo: ['spider-man-3'],
  threads: [], characters: ['蜘蛛侠(加菲)', '格温', '电光人', '绿魔(哈里)'],
  postCredits: 0, eggTip: '看完再回看《英雄无归》天台接人那一幕,你会明白加菲当时的表情。',
},

/* ================= 前代与番外:X战警 & 死侍 ================= */
{
  id: 'xmen-1', title: 'X战警', enTitle: 'X-Men (2000)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2000-07-14', chron: null, storyYear: null, runtime: 104, tier: 'optional',
  rating: 7.3, emoji: '❌',
  tagline: '现代超英电影的真正起点。',
  synopsis: '变种人在人类社会中挣扎求存,X教授与万磁王理念分裂。金刚狼与小淘气误入战局,自此开启二十年的福斯变种人宇宙。',
  whyWatch: '为《死侍与金刚狼》与未来 MCU 变种人时代打底。休·杰克曼的金刚狼从这里开始。',
  prereq: [], leadsTo: ['xmen-2', 'deadpool-wolverine'],
  threads: [], characters: ['金刚狼', 'X教授', '万磁王', '小淘气', '暴风女', '镭射眼', '琴·葛蕾'],
  postCredits: 0, eggTip: '2000 年的变种人电影敢拍成政治寓言,放当年是相当大胆的。',
},
{
  id: 'xmen-2', title: 'X战警2', enTitle: 'X2: X-Men United (2003)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2003-05-02', chron: null, storyYear: null, runtime: 134, tier: 'optional',
  rating: 7.4, emoji: '🧬',
  tagline: '系列口碑巅峰之一。',
  synopsis: '军方科学家史崔克突袭X学院,X战警被迫与万磁王联手。金刚狼在此直面自己被改造的过去——武器X计划。',
  whyWatch: '金刚狼身世的核心篇章,夜行者开场的白宫突袭堪称影史名场面。',
  prereq: ['xmen-1'], leadsTo: ['xmen-3'],
  threads: [], characters: ['金刚狼', 'X教授', '万磁王', '夜行者', '琴·葛蕾', '史崔克'],
  postCredits: 0, eggTip: '结尾湖面的凤凰之影,预告了下一部的黑凤凰事件。',
},
{
  id: 'xmen-3', title: 'X战警3:背水一战', enTitle: 'X-Men: The Last Stand (2006)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2006-05-26', chron: null, storyYear: null, runtime: 104, tier: 'optional',
  rating: 6.6, emoji: '💉',
  tagline: '黑凤凰觉醒,初代三部曲仓促收尾。',
  synopsis: '「治愈变种基因」的药剂引爆两派全面战争,复活的琴·葛蕾被黑凤凰人格吞噬。初代阵容在此谢幕。',
  whyWatch: '口碑争议大,但《金刚狼3》《死侍与金刚狼》多处引用其后果。快速看过即可。',
  prereq: ['xmen-2'], leadsTo: ['logan'],
  threads: [], characters: ['金刚狼', '黑凤凰', '琴·葛蕾', 'X教授', '万磁王', '野兽'],
  postCredits: 1, eggTip: '彩蛋暗示X教授意识转移——这个设定后来真被多次使用。',
},
{
  id: 'first-class', title: 'X战警:第一战', enTitle: 'X-Men: First Class (2011)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2011-06-03', chron: null, storyYear: null, runtime: 131, tier: 'optional',
  rating: 7.7, emoji: '♟️',
  tagline: '1962:查尔斯与埃里克的相遇与决裂。',
  synopsis: '冷战背景下,年轻的查尔斯与集中营幸存者埃里克联手对抗地狱火俱乐部,却在古巴导弹危机的沙滩上走向永别。一枚硬币,一颗子弹,一生挚友。',
  whyWatch: '前传三部曲的最佳开局,法鲨与一美的双雄对手戏堪称表演课。理解万磁王,从这一部开始。',
  prereq: [], leadsTo: ['dofp'],
  threads: [], characters: ['X教授', '万磁王', '查尔斯', '埃里克', '魔形女', '野兽'],
  postCredits: 0, eggTip: '金刚狼的客串只有一句台词,但可能是影史最贵的一句脏话。',
},
{
  id: 'dofp', title: 'X战警:逆转未来', enTitle: 'X-Men: Days of Future Past (2014)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2014-05-23', chron: null, storyYear: null, runtime: 132, tier: 'optional',
  rating: 7.9, emoji: '⏮️',
  tagline: '新老两代同框,系列最高完成度。',
  synopsis: '未来的哨兵机器人几乎灭绝变种人,金刚狼的意识被送回 1973 年,撮合决裂的查尔斯与埃里克,阻止那颗改变历史的子弹。',
  whyWatch: 'X战警系列的《终局之战》,一部看懂新老两代阵容。快银的「子弹时间」厨房戏是影史级名场面。',
  prereq: ['first-class', 'xmen-3'], leadsTo: ['logan', 'deadpool-wolverine'],
  threads: [], characters: ['金刚狼', 'X教授', '万磁王', '魔形女', '快银(X)', '哨兵'],
  postCredits: 1, eggTip: '这部之后,老三部曲的悲剧时间线被正式抹除——官方洗牌。',
},
{
  id: 'logan', title: '金刚狼3:殊死一战', enTitle: 'Logan (2017)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2017-03-03', chron: null, storyYear: null, runtime: 137, tier: 'recommended',
  rating: 8.1, emoji: '🌵',
  tagline: '超英电影拍成西部片挽歌,休·杰克曼的告别。',
  synopsis: '2029 年,变种人近乎绝迹。衰老中毒的罗根护送着失智的X教授和基因克隆女孩X-23,横穿美国,走向最后的安息之地。',
  whyWatch: '不看它,《死侍与金刚狼》一半的梗和全部的情感重量都接不住。R 级、悲怆、影史留名——超英电影可以是严肃电影的证明。',
  prereq: ['xmen-1'], leadsTo: ['deadpool-wolverine'],
  threads: [], characters: ['金刚狼', '罗根', 'X教授', 'X-23', '劳拉'],
  postCredits: 0, eggTip: '片尾那个横放的十字架成为「X」——无声胜万言。',
},
{
  id: 'deadpool-1', title: '死侍', enTitle: 'Deadpool (2016)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2016-02-12', chron: null, storyYear: null, runtime: 108, tier: 'recommended',
  rating: 8.0, emoji: '🌶️',
  tagline: 'R 级嘴炮雇佣兵,打破第四面墙鼻祖。',
  synopsis: '绝症雇佣兵韦德接受地下改造获得不死之身,却被毁容。他化身死侍展开复仇,顺便把整个超英类型片吐槽了个遍。',
  whyWatch: '《死侍与金刚狼》的前置必修课。小成本逆袭的类型片革命,笑点密度至今无人能敌。',
  prereq: [], leadsTo: ['deadpool-2'],
  threads: [], characters: ['死侍', '韦德', '瓦内莎', '钢力士', '青少年弹头'],
  postCredits: 1, eggTip: '片尾致敬《春天不是读书天》的睡袍彩蛋,连彩蛋都要吐槽彩蛋文化。',
},
{
  id: 'deadpool-2', title: '死侍2', enTitle: 'Deadpool 2 (2018)', type: 'movie', universe: 'xmen',
  phase: 0, release: '2018-05-18', chron: null, storyYear: null, runtime: 119, tier: 'recommended',
  rating: 7.6, emoji: '🍼',
  tagline: '电索登场,X特攻队全灭名场面。',
  synopsis: '痛失挚爱的韦德在拯救叛逆变种少年的过程中,与来自未来的电索不打不相识,组建了存活率感人的「X特攻队」。',
  whyWatch: '多米诺与电索都是《死侍与金刚狼》的前情;彩蛋里死侍拿着时间装置乱改历史,恰好是第三部多元宇宙玩法的预演。',
  prereq: ['deadpool-1'], leadsTo: ['deadpool-wolverine'],
  threads: [], characters: ['死侍', '电索', '多米诺', '火拳', '钢力士'],
  postCredits: 2, eggTip: '彩蛋里死侍回去「修复」了系列黑历史,包括枪杀《金刚狼前传》里的自己。',
},

/* ================= 前代与番外:其他 ================= */
{
  id: 'dd-netflix', title: '夜魔侠(网飞版)', enTitle: 'Daredevil (2015-2018)', type: 'series', universe: 'netflix',
  phase: 0, release: '2015-04-10', chron: null, storyYear: null, runtime: 1950, episodes: 39, tier: 'recommended',
  rating: 8.6, emoji: '🦯',
  tagline: '地狱厨房的守护神,漫威剧集的暴力美学巅峰。',
  synopsis: '白天是盲人律师,夜晚是私刑者。马特·默多克与犯罪之王金并在地狱厨房展开三季拉锯,走廊长镜头打戏定义了什么叫「拳拳到肉」。',
  whyWatch: '《夜魔侠:重生》的全部人物根基(马特、金并、惩罚者、子弹眼)都在这三季里。就算不看重生,它本身也是漫威剧集的质量天花板。',
  prereq: [], leadsTo: ['daredevil-ba'],
  threads: [], characters: ['夜魔侠', '马特·默多克', '金并', '惩罚者', '艾丽卡', '弗吉', '凯伦'],
  postCredits: 0, eggTip: '每季必有一场「一镜到底走廊/楼梯战」,是全剧的仪式性名场面。',
},
{
  id: 'agents-shield', title: '神盾局特工', enTitle: 'Agents of S.H.I.E.L.D.', type: 'series', universe: 'tv',
  phase: 0, release: '2013-09-24', chron: null, storyYear: null, runtime: 5850, episodes: 136, tier: 'optional',
  rating: 7.5, emoji: '🛰️',
  tagline: '科尔森特工的七季长跑。',
  synopsis: '在《复联1》中「牺牲」的科尔森特工复活,率领一支小队处理超自然事件。第一季中段与《美队2》神盾局崩塌的联动是美剧史经典操作。',
  whyWatch: '体量巨大(136集),与电影宇宙的联动集中在前几季。真爱粉或时间充裕再入坑,入坑请至少撑到第一季第17集。',
  prereq: ['avengers', 'cap-2'], leadsTo: [],
  threads: ['shield'], characters: ['科尔森', '黛西', '梅', '菲兹', '西蒙斯', '震波女'],
  postCredits: 0, eggTip: '第四季「机器人革命+地狱火」被普遍认为是全剧巅峰。',
},
{
  id: 'venom-1', title: '毒液:致命守护者', enTitle: 'Venom (2018)', type: 'movie', universe: 'sony',
  phase: 0, release: '2018-10-05', chron: null, storyYear: null, runtime: 112, tier: 'optional',
  rating: 6.6, emoji: '👅',
  tagline: '一人一虫的相声宇宙。',
  synopsis: '落魄记者埃迪被外星共生体缠上,两个失败者共用一具身体,吵吵闹闹拯救旧金山。',
  whyWatch: '索尼自家宇宙,与 MCU 仅在《英雄无归》彩蛋轻微交汇。当爆米花喜剧看很快乐。',
  prereq: [], leadsTo: ['venom-2'],
  threads: [], characters: ['毒液', '埃迪', '安妮'],
  postCredits: 2, eggTip: '彩蛋预告屠杀登场;另一个彩蛋竟是《蜘蛛侠:平行宇宙》片段。',
},
{
  id: 'venom-2', title: '毒液2:屠杀开始', enTitle: 'Venom: Let There Be Carnage (2021)', type: 'movie', universe: 'sony',
  phase: 0, release: '2021-10-01', chron: null, storyYear: null, runtime: 97, tier: 'optional',
  rating: 5.9, emoji: '🩸',
  tagline: '「屠杀」降临,片尾彩蛋连通 MCU。',
  synopsis: '连环杀手克莱图斯获得红色共生体「屠杀」,埃迪与毒液这对欢喜冤家被迫正面迎战。',
  whyWatch: '正片快餐,但片尾彩蛋里毒液被闪到 MCU 世界看到了蜘蛛侠新闻——这就是《英雄无归》里那点共生体的来历。',
  prereq: ['venom-1'], leadsTo: ['spider-man-3'],
  threads: [], characters: ['毒液', '埃迪', '屠杀', '克莱图斯'],
  postCredits: 1, eggTip: '这个彩蛋是索尼宇宙与 MCU 迄今最直接的一次握手。',
},
{
  id: 'spider-verse-1', title: '蜘蛛侠:平行宇宙', enTitle: 'Spider-Man: Into the Spider-Verse', type: 'movie', universe: 'spiderverse',
  phase: 0, release: '2018-12-14', chron: null, storyYear: null, runtime: 117, tier: 'recommended',
  rating: 8.4, emoji: '🎨',
  tagline: '奥斯卡最佳动画,漫画美学革命。',
  synopsis: '布鲁克林少年迈尔斯被蜘蛛咬伤当天,对撞机把多个宇宙的蜘蛛侠拽到了他的世界。任何人都能戴上面罩——这是属于所有蜘蛛侠的故事。',
  whyWatch: '严格说不属于任何真人宇宙,但它把「多元宇宙+蜘蛛侠」玩得比谁都早、都好。动画技术直接改变了行业。必看的番外。',
  prereq: [], leadsTo: ['spider-verse-2'],
  threads: [], characters: ['迈尔斯', '彼得·B·帕克', '格温(蜘蛛格温)', '金并', '潘妮', '暗影蜘蛛侠'],
  postCredits: 1, eggTip: '彩蛋里 2099 蜘蛛侠穿越回 1967 版动画,复刻「蜘蛛侠互指」名梗。',
},
{
  id: 'spider-verse-2', title: '蜘蛛侠:纵横宇宙', enTitle: 'Spider-Man: Across the Spider-Verse', type: 'movie', universe: 'spiderverse',
  phase: 0, release: '2023-06-02', chron: null, storyYear: null, runtime: 140, tier: 'recommended',
  rating: 8.5, emoji: '🖌️',
  tagline: '每一帧都是壁纸,悬念留到第三部。',
  synopsis: '格温邀请迈尔斯进入横跨多元宇宙的「蜘蛛联盟」,但联盟守护的「宿命事件」教条与迈尔斯的信念正面相撞。他选择对抗所有蜘蛛侠。',
  whyWatch: '视觉与叙事野心双双拉满的续作,六种画风同屏。注意:结尾是大悬念,第三部《超越宇宙》仍在制作中。',
  prereq: ['spider-verse-1'], leadsTo: [],
  threads: [], characters: ['迈尔斯', '格温', '斑点', '2099蜘蛛侠', '朋克蜘蛛侠'],
  postCredits: 0, eggTip: '斑点的跨宇宙乱入镜头里藏满了历代蜘蛛侠彩蛋,可逐帧考古。',
},
];

/* ---------- 工具索引 ---------- */
MARVEL.byId = {};
MARVEL.WORKS.forEach(w => { MARVEL.byId[w.id] = w; });

/* 勾选完成时随机弹出的台词 */
MARVEL.QUOTES = [
  { en: 'I am Iron Man.', cn: '我就是钢铁侠。' },
  { en: 'I can do this all day.', cn: '我可以打上一整天。' },
  { en: 'Avengers, assemble!', cn: '复仇者,集结!' },
  { en: 'We are Groot.', cn: '我们是格鲁特。' },
  { en: 'Wakanda Forever!', cn: '瓦坎达万岁!' },
  { en: 'Higher, further, faster.', cn: '更高,更远,更快。' },
  { en: 'I love you 3000.', cn: '爱你三千遍。' },
  { en: 'Dormammu, I\'ve come to bargain.', cn: '多玛姆,我是来谈判的。' },
  { en: 'With great power comes great responsibility.', cn: '能力越大,责任越大。' },
  { en: 'I\'m always angry.', cn: '我一直都在愤怒。' },
  { en: 'Whatever it takes.', cn: '不惜一切代价。' },
  { en: 'That\'s my secret, Cap.', cn: '这就是我的秘密,队长。' },
  { en: 'Glorious purpose!', cn: '光荣的使命!' },
  { en: 'Maximum effort!', cn: '全力以赴!' },
];
