/* ==========================================================================
   MARVEL 宇宙观影指挥中心 — 宇宙百科(大事件 & 名词典)
   事件的 desc/consequence 含剧透,keyWork 未看且开启剧透保护时会被遮罩。
   chron 用于把事件插入「故事时间线」视图。
   ========================================================================== */

window.MARVEL = window.MARVEL || {};

MARVEL.EVENTS = [
{
  id: 'super-soldier', name: '超级士兵计划', en: 'Project Rebirth', emoji: '💉', year: '1943',
  chron: 11, keyWork: 'cap-1',
  cause: '二战胶着,盟军急需对抗九头蛇的秘密武器,厄斯金博士研发出超级士兵血清。',
  desc: '瘦弱的史蒂夫·罗杰斯成为唯一成功实验体;厄斯金遇刺后血清配方失传,此后八十年,无数势力为复刻血清前赴后继。',
  consequence: '美国队长诞生;血清残余脉络贯穿浩克、艾布拉罕计划、碎旗者、US Agent 与红浩克——半个宇宙的怪物都是它的回声。',
  works: ['cap-1', 'hulk', 'falcon-ws', 'brave-new-world'],
},
{
  id: 'battle-of-ny', name: '纽约之战', en: 'The Battle of New York', emoji: '🌆', year: '2012',
  chron: 71, keyWork: 'avengers',
  cause: '洛基携权杖与宇宙魔方打开传送门,引齐塔瑞军团入侵地球。',
  desc: '六位英雄首次集结守卫曼哈顿,核弹飞向虫洞,托尼一去(差点)不返。全球第一次知道:外星人是真的,英雄也是。',
  consequence: 'MCU 的坐标原点:托尼的创伤、神盾局的野心、泽莫的仇恨、金并的重建生意、凯特的偶像崇拜——全部从这一天长出来。《终局之战》时间劫案更是三度重返此地。',
  works: ['avengers', 'iron-man-3', 'hawkeye', 'endgame', 'loki-s1'],
},
{
  id: 'shield-fall', name: '神盾局崩塌', en: 'The Fall of S.H.I.E.L.D.', emoji: '🛰️', year: '2014',
  chron: 101, keyWork: 'cap-2',
  cause: '九头蛇自二战后渗透神盾局七十年,「洞察计划」的三艘天空母舰即将猎杀两千万潜在威胁。',
  desc: '队长与黑寡妇把神盾局连同九头蛇一起掀翻,所有机密文件公开于世,弗瑞「死亡」隐退。',
  consequence: '超英监管真空直接导致《奥创纪元》的私造 AI 与《内战》的协议之争;失业的特工与流散的技术养活了此后十年的各路反派。',
  works: ['cap-2', 'aou', 'civil-war', 'agents-shield'],
},
{
  id: 'sokovia', name: '索科维亚事件', en: 'The Sokovia Incident', emoji: '🏙️', year: '2015',
  chron: 131, keyWork: 'aou',
  cause: '托尼用洛基权杖中的心灵宝石秘密开发和平守护 AI,奥创觉醒后判定人类才是威胁。',
  desc: '奥创将索科维亚整城升空,欲造成灭绝级撞击;复仇者疏散平民并炸毁浮岛,快银战死,幻视诞生。',
  consequence: '死伤与恐慌催生《索科维亚协议》;失去家园的旺达与双亲死于斯塔克炸弹的旧账,让她此后的每一步都踩在裂缝上。',
  works: ['aou', 'civil-war', 'wandavision'],
},
{
  id: 'civil-war-event', name: '复仇者内战', en: 'The Avengers Civil War', emoji: '⚔️', year: '2016',
  chron: 151, keyWork: 'civil-war',
  cause: '《索科维亚协议》要求英雄接受联合国监管;泽莫男爵伪造冬兵恐袭,点燃火药桶。',
  desc: '钢铁侠与美国队长各执一端,十二人机场对决;真相揭穿时——冬兵杀死了托尼的父母——联盟彻底破裂,队长弃盾出走。',
  consequence: '复仇者分裂五年,直接导致《无限战争》各自为战的溃败;泽莫成为唯一「赢了」的反派。',
  works: ['civil-war', 'black-widow', 'infinity-war', 'falcon-ws'],
},
{
  id: 'the-snap', name: '无限响指', en: 'The Snap', emoji: '🫰', year: '2018',
  chron: 221, keyWork: 'infinity-war',
  cause: '灭霸坚信宇宙资源有限,集齐六颗无限宝石,要「公平地」随机抹除一半生命。',
  desc: '瓦坎达战场上,幻视两度赴死仍未能阻止;灭霸打响响指,全宇宙一半生灵化为飞灰,英雄们第一次彻底输了。',
  consequence: '宇宙进入五年「大消失」;幸存者的创伤、消失者归来后的错位(《猎鹰与冬兵》的难民危机、彼得的同学没长大),成为第四阶段所有故事的底色。',
  works: ['infinity-war', 'ant-man-wasp', 'endgame', 'falcon-ws', 'spider-man-2'],
},
{
  id: 'the-blip', name: '五年空窗', en: 'The Blip', emoji: '🕳️', year: '2018-2023',
  chron: 225, keyWork: 'endgame',
  cause: '响指之后,世界不得不带着一半人口继续运转。',
  desc: '五年间:队长开互助会,娜塔莎独守总部,克林特化身浪人,托尼归隐生女,雷神一蹶不振。宇宙学会了与巨大的缺口共存。',
  consequence: '正因为有这五年,托尼的女儿摩根、克林特的血债、雷神的啤酒肚才有了重量;逆转之后「凭空多出一半人」的混乱同样贯穿后续。',
  works: ['endgame', 'spider-man-2', 'falcon-ws', 'hawkeye', 'wandavision'],
},
{
  id: 'time-heist', name: '时间劫案与逆转响指', en: 'The Time Heist', emoji: '⏱️', year: '2023',
  chron: 231, keyWork: 'endgame',
  cause: '蚁人从量子领域归来,带来「时间旅行」的可能;复仇者重聚,回到过去偷取六颗宝石。',
  desc: '三路人马重访 2012 纽约、2013 阿斯加德、2014 沃米尔与 1970 新泽西;班纳打响逆转响指带回所有人,托尼以生命打出终结之响。',
  consequence: '消失的一半归来;娜塔莎与托尼永别;2012 洛基带魔方逃逸(直通《洛基》)、2014 灭霸舰队被连根拔起。时间分支的口子,从此再没合上。',
  works: ['endgame', 'loki-s1', 'spider-man-2'],
},
{
  id: 'westview', name: '西景镇异常', en: 'The Westview Anomaly', emoji: '📺', year: '2023',
  chron: 251, keyWork: 'wandavision',
  cause: '接连失去至亲的旺达,在幻视本该安家的空地上情绪决堤。',
  desc: '混沌魔法将整座小镇改写成历代情景喜剧,数千居民被迫「出演」;剧天局围城,阿加莎潜伏窃力。',
  consequence: '旺达正式觉醒为绯红女巫并获得黑暗神书——直通《疯狂多元宇宙》的黑化;她凭空造出的双子,则是《阿加莎》与未来青年复仇者的伏笔。',
  works: ['wandavision', 'mom', 'agatha'],
},
{
  id: 'timeline-split', name: '神圣时间线炸裂', en: 'The Multiversal Fracture', emoji: '🌳', year: '时间之外',
  chron: 241, keyWork: 'loki-s1',
  cause: '西尔维在时间尽头的城堡杀死「残存者」,无人再修剪时间分支。',
  desc: '神圣时间线瞬间炸成无数分支,康的无限变体在各宇宙苏醒;TVA 从修剪机构变成救火队。',
  consequence: '多元宇宙时代正式开幕:《英雄无归》的三虫同框、《疯狂多元宇宙》的入侵、《死侍与金刚狼》的时间线安乐死,都是这一剑的涟漪。',
  works: ['loki-s1', 'spider-man-3', 'mom', 'loki-s2', 'deadpool-wolverine'],
},
{
  id: 'spell-gone-wrong', name: '失控的遗忘咒', en: 'The Broken Spell', emoji: '🕸️', year: '2024',
  chron: 301, keyWork: 'spider-man-3',
  cause: '身份曝光毁掉生活,彼得请奇异博士施展让全世界遗忘「蜘蛛侠是彼得·帕克」的咒语,却五次三番修改条件。',
  desc: '咒语失控撕开多元宇宙,拽来了认识彼得·帕克的所有人——两代蜘蛛侠与五大反派同台。',
  consequence: '梅姨之死教会彼得那句话的分量;最终他选择让全世界(包括 MJ 和内德)忘记自己。三代同框治愈了前代的遗憾,也预告了多元宇宙的脆弱。',
  works: ['spider-man-3', 'mom', 'brand-new-day'],
},
{
  id: 'incursion', name: '宇宙入侵警告', en: 'Incursions', emoji: '💥', year: '2025',
  chron: 311, keyWork: 'mom',
  cause: '梦游、黑暗神书与达克霍德的滥用,让宇宙之间的壁垒出现裂缝。',
  desc: '《疯狂多元宇宙》抛出「入侵」概念:两个宇宙相撞,至少毁灭其一。克莉带走斯特兰奇去处理的,正是一场入侵。',
  consequence: '这是《毁灭日》与《秘密战争》的核心物理法则——漫画中,秘密战争正是所有宇宙入侵坍缩后的终局。',
  works: ['mom', 'brave-new-world', 'doomsday', 'secret-wars'],
},
{
  id: 'kang-dynasty-fall', name: '康议会与时间之树', en: 'The Council of Kangs', emoji: '⏰', year: '时间之外',
  chron: 431, keyWork: 'loki-s2',
  cause: '时间织机过载,TVA 的谎言瓦解;量子领域的征服者蠢蠢欲动。',
  desc: '洛基牺牲自由撑起多元宇宙之树;蚁人一家挫败征服者康;但彩蛋里,无数康的变体正济济一堂。',
  consequence: '康的威胁悬而未决之际,毁灭博士登上主舞台——两任「多元宇宙大反派」的交接,正是通往《毁灭日》的暗门。',
  works: ['loki-s2', 'quantumania', 'doomsday'],
},
{
  id: 'new-avengers', name: '新复仇者成立', en: 'The New Avengers', emoji: '🛡️', year: '2027',
  chron: 501, keyWork: 'thunderbolts',
  cause: '瓦伦蒂娜的哨兵计划失控,「虚空」吞噬纽约;一群被她设局灭口的反英雄反而救了场。',
  desc: '叶莲娜把鲍勃从虚空里拉回来;瓦伦蒂娜顺势召开发布会,把这支草台班子册封为「新复仇者」。',
  consequence: '初代谢幕八年后,复仇者之名重新挂牌——但商标权在山姆手里,队伍在瓦伦蒂娜手里。这道裂缝,将在《毁灭日》前摊牌。',
  works: ['thunderbolts', 'brave-new-world', 'doomsday'],
},
];

/* ---------- 名词典 ----------
   def 尽量无剧透;spoiler 为进阶剧透内容(受剧透保护遮罩)。 */
MARVEL.GLOSSARY = [
{ term: '无限宝石', en: 'Infinity Stones', emoji: '💎',
  def: '创世大爆炸凝成的六颗奇点:空间、时间、现实、力量、心灵、灵魂。各自掌管宇宙的一个基本维度,集齐即近乎全能。',
  spoiler: '灭霸用它们抹除半数生命;《终局之战》后本时间线的六颗已尽数化为原子,但每个宇宙都有自己的一套。',
  works: ['thor-2', 'gotg', 'infinity-war', 'endgame'] },
{ term: '宇宙魔方', en: 'Tesseract', emoji: '🧊',
  def: '蓝色立方体,曾被奥丁藏于地球、红骷髅夺走、神盾局打捞。它其实是空间宝石的封装外壳。',
  spoiler: '洛基 2012 年借它逃跑,引出 TVA 剧情;正史线中被灭霸捏碎取石。',
  works: ['cap-1', 'avengers', 'captain-marvel', 'loki-s1'] },
{ term: '振金', en: 'Vibranium', emoji: '🔩',
  def: '陨石带来的宇宙金属,能吸收与释放动能,近乎无坚不摧。地球已知矿藏几乎全在瓦坎达。',
  spoiler: '队长之盾、黑豹战衣、幻视之躯皆由它铸成;《瓦坎达万岁》揭示海底塔洛坎同样拥有振金,由此引发大战。',
  works: ['cap-1', 'black-panther', 'wakanda-forever'] },
{ term: '超级士兵血清', en: 'Super-Soldier Serum', emoji: '💉',
  def: '厄斯金博士的造人奇迹:放大使用者的体能,也放大其本性——「好人更好,坏人更坏」。',
  spoiler: '成功品只有队长;失败品与仿制品包括浩克、憎恶、红骷髅、冬兵、碎旗者与红浩克——一部血清失控史就是半部 MCU 反派史。',
  works: ['cap-1', 'hulk', 'falcon-ws', 'brave-new-world'] },
{ term: '神盾局', en: 'S.H.I.E.L.D.', emoji: '🛰️',
  def: '国土战略防御攻击与后勤保障局:卡特特工与霍华德·斯塔克创立的超级情报机构,复仇者计划的娘家。',
  spoiler: '2014 年因九头蛇渗透而崩塌解散;弗瑞此后转入幕后,在天空母舰与太空站里继续他的暗棋。',
  works: ['iron-man', 'avengers', 'cap-2', 'agents-shield'] },
{ term: '九头蛇', en: 'HYDRA', emoji: '🐙',
  def: '「砍掉一个头,还会长出两个」——起源于二战的邪恶科学组织,红骷髅是初代首脑。',
  spoiler: '战后借「回形针行动」潜入神盾局深耕七十年,冬兵是其王牌杀手;《美队2》被连根拔起后仅剩残党。',
  works: ['cap-1', 'cap-2', 'aou'] },
{ term: '皮姆粒子', en: 'Pym Particles', emoji: '🔬',
  def: '汉克·皮姆博士发现的亚原子粒子,可任意改变物体大小与密度。蚁人与黄蜂女的立身之本。',
  spoiler: '缩小到极致即坠入量子领域;《终局之战》的时间旅行全靠它当「燃料」,库存一度只够每人往返一次。',
  works: ['ant-man', 'ant-man-wasp', 'endgame'] },
{ term: '量子领域', en: 'Quantum Realm', emoji: '⚛️',
  def: '亚原子尺度下的隐秘宇宙,时间与空间的规则在这里失效。',
  spoiler: '斯科特被困于此五小时、外界已过五年,由此启发时间劫案;《量子狂潮》揭示其深处竟有文明——以及被放逐的征服者康。',
  works: ['ant-man', 'ant-man-wasp', 'endgame', 'quantumania'] },
{ term: '阿斯加德', en: 'Asgard', emoji: '🏰',
  def: '九界之巅的黄金国度,奥丁王朝统治之地。彩虹桥由守门人海姆达尔执掌。',
  spoiler: '《诸神黄昏》中毁于苏尔特尔之手;幸存者移居挪威建立「新阿斯加德」,由女武神任王。',
  works: ['thor', 'thor-2', 'thor-ragnarok', 'thor-lt'] },
{ term: '克里与斯克鲁', en: 'Kree & Skrulls', emoji: '👽',
  def: '两大宿敌外星文明:蓝皮肤的军国主义克里帝国,与能变形拟态的流亡种族斯克鲁人。',
  spoiler: '《惊奇队长》反转:斯克鲁其实是难民;三十年后承诺落空,激进派发动《秘密入侵》,渗透到了人类权力顶层。',
  works: ['captain-marvel', 'secret-invasion', 'marvels'] },
{ term: '十环', en: 'The Ten Rings', emoji: '⭕',
  def: '既是文武执掌千年的犯罪组织,也是他手腕上来历不明的十只能量环。《钢铁侠》的绑匪正是打着它的旗号。',
  spoiler: '尚气继承十环后,彩蛋显示它们在向宇宙深处发送信标——发信对象至今成谜。',
  works: ['iron-man', 'shang-chi'] },
{ term: '至圣所', en: 'Sanctum Sanctorum', emoji: '🏛️',
  def: '卡玛泰姬在纽约、伦敦、香港设立的三座结界堡垒,共同守护地球免受神秘侧入侵。',
  spoiler: '纽约至圣所先后由斯特兰奇与王主持;《无限战争》开场它挨的那一炮,宣告了灭霸大军压境。',
  works: ['doctor-strange', 'infinity-war', 'spider-man-3'] },
{ term: '黑暗神书 / 维山帝之书', en: 'Darkhold & Book of Vishanti', emoji: '📕',
  def: '魔法侧的矛与盾:黑暗神书是腐蚀使用者的禁忌魔典,维山帝之书则是传说中的正道宝典。',
  spoiler: '旺达借黑暗神书梦游多元宇宙,最终推塌卡玛山摧毁了所有宇宙的黑暗神书副本——代价是把自己也埋在山下。',
  works: ['wandavision', 'mom', 'agatha'] },
{ term: '混沌魔法', en: 'Chaos Magic', emoji: '🌹',
  def: '凭空改写现实的禁忌之力,远超普通法术的量级。传说中的使用者被称为「绯红女巫」。',
  spoiler: '旺达并非因心灵宝石获得能力——宝石只是唤醒了她与生俱来的混沌魔法,黑暗神书预言她将「统治或毁灭宇宙」。',
  works: ['wandavision', 'mom'] },
{ term: 'TVA', en: 'Time Variance Authority', emoji: '🏢',
  def: '时间变异管理局:存在于时间之外的官僚机构,专职「修剪」偏离既定轨道的时间分支。',
  spoiler: '其创立者正是康的变体「残存者」,所谓神圣时间线不过是他修剪出的盆栽;洛基第二季后,TVA 转型为多元宇宙的守望者。',
  works: ['loki-s1', 'loki-s2', 'deadpool-wolverine'] },
{ term: '变体', en: 'Variant', emoji: '👥',
  def: '同一个「你」在不同时间分支/宇宙中的版本。可能性格迥异,甚至物种不同(比如鳄鱼洛基)。',
  spoiler: '康的恐怖之处正在于此:杀死一个征服者,还有一整个议会的变体;而唐尼从托尼到毁灭博士的「跨角色回归」,官方也玩起了变体梗。',
  works: ['loki-s1', 'mom', 'deadpool-wolverine'] },
{ term: '多元宇宙', en: 'The Multiverse', emoji: '🌌',
  def: '无数平行宇宙构成的整体,每个选择都可能分裂出新的世界。MCU 主宇宙编号 616,神奇四侠所在为 828。',
  spoiler: '神圣时间线炸裂后多元宇宙彻底放飞;「入侵」(宇宙相撞)将是《秘密战争》的引信。',
  works: ['loki-s1', 'spider-man-3', 'mom', 'fantastic-four'] },
{ term: '齐塔瑞', en: 'Chitauri', emoji: '🛸',
  def: '受蜂巢意识驱动的外星生物军团,纽约之战的入侵方,背后金主是灭霸。',
  spoiler: '战后残骸催生了秃鹫的军火生意与神盾局的诸多黑科技——纽约之战的垃圾,养活了半个地下产业链。',
  works: ['avengers', 'spider-man-1'] },
{ term: '沃米尔', en: 'Vormir', emoji: '🪦',
  def: '宇宙尽头的荒芜星球,灵魂宝石的安放之地,由一位意想不到的守墓人看管。',
  spoiler: '规则残酷:以所爱之人的灵魂交换宝石。卡魔拉与娜塔莎先后在此陨落;守墓人是化作幽魂的红骷髅。',
  works: ['infinity-war', 'endgame'] },
{ term: '共生体', en: 'Symbiote', emoji: '👅',
  def: '来自外星的液态寄生生命,与宿主共享力量并放大其阴暗面。毒液与屠杀皆属此族。',
  spoiler: '主要活跃于索尼宇宙;《毒液2》彩蛋中埃迪曾短暂闪到 MCU,留下过一小滴共生体——这颗种子还没发芽。',
  works: ['raimi-3', 'venom-1', 'venom-2', 'spider-man-3'] },
{ term: '变种人', en: 'Mutants', emoji: '🧬',
  def: '因 X 基因天生拥有超能力的人类亚种。X战警系列的根基,曾因版权归属长期缺席 MCU。',
  spoiler: '回归进行时:惊奇少女被确认为变种人、《黑豹2》的纳摩自称「K\'uk\'ulkan 变种人」、光束登场于《惊奇队长2》彩蛋——X战警正式并入只差临门一脚。',
  works: ['xmen-1', 'ms-marvel', 'marvels', 'deadpool-wolverine'] },
{ term: '塔洛坎', en: 'Talokan', emoji: '🌊',
  def: '隐匿深海的玛雅后裔文明,与瓦坎达并列的振金强国,由飞踝之神纳摩统治。',
  spoiler: '为阻止水面世界探采海底振金,纳摩曾水淹瓦坎达;停战协议脆弱,这位「变种人」之王迟早重返牌桌。',
  works: ['wakanda-forever'] },
{ term: '天神族', en: 'Celestials', emoji: '🗿',
  def: '宇宙最古老的至高存在,身躯以行星为尺度。星爵的父亲伊戈、审判者阿里瑟姆皆属此族。',
  spoiler: '《永恒族》揭示:天神族在宿主行星内孵化新神,地球本身就是一枚蛋;胎死腹中的提亚穆特石像至今矗立在印度洋——《美队4》的「天神岛」就是它。',
  works: ['gotg2', 'eternals', 'brave-new-world'] },
];
